---
dependency:
  name: galaxy
  requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "${ANSIBLE_TEST_DISTRO}"
    command: ${ANSIBLE_TEST_DOCKER_COMMAND}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root
        configure_backup_restic: true
  playbooks:
    converge: "${ANSIBLE_TEST_PLAYBOOK_PATH}"
...
