---
- name: Validate the runtime environment before running the configuration process
  ansible.builtin.import_tasks: pre-flight-checks.yaml
  tags:
    - always

- name: Load a variable file based on the OS type, or a default if not found
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - "default.yaml"
  tags:
    - always

- name: Setup OS
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "setup-{{ ansible_distribution }}.yaml"
    - "setup-{{ ansible_os_family }}.yaml"

- name: Ensure handlers are notified now
  ansible.builtin.meta: flush_handlers
