---
ansible_python_interpreter: auto_silent
# Automatically accept new host keys for hosts in the inventory
ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
ansible_user: root
cam_3_rtps_password: "{{ vault_cam_3_rtps_password }}"
cam_3_rtps_username: "{{ vault_cam_3_rtps_username }}"
frigate_http_endpoint_fqdn: "hl01.{{ edge_environment_root_fqdn }}"
grafana_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
home_assistant_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
home_assistant_internal_url_home: "http://{{ home_assistant_http_endpoint_fqdn }}:{{ home_assistant_user_interface_host_port }}"
home_assistant_secrets:
  country: "{{ vault_home_assistant_secrets.country }}"
  currency: "{{ vault_home_assistant_secrets.currency }}"
  elevation_home: "{{ vault_home_assistant_secrets.elevation_home }}"
  latitude_home: "{{ vault_home_assistant_secrets.latitude_home }}"
  longitude_home: "{{ vault_home_assistant_secrets.longitude_home }}"
  name_home: "{{ vault_home_assistant_secrets.name_home }}"
  spotify_client_id: "{{ vault_home_assistant_secrets.spotify_client_id }}"
  spotify_client_secret: "{{ vault_home_assistant_secrets.spotify_client_secret }}"
  telegram_bot_api_key: "{{ vault_home_assistant_secrets.telegram_bot_api_key }}"
  telegram_bot_allowed_chat_ids: "{{ vault_home_assistant_secrets.telegram_bot_allowed_chat_ids }}"
  timezone_home: "{{ vault_home_assistant_secrets.timezone_home }}"
home_lab_configuration_directory_path: "/etc/ferrarimarco-home-lab"
home_lab_node_ssh_public_key_path: "ssh/home-lab-node-ssh-key.pub"
home_lab_runtime_directory_path: "/var/lib/ferrarimarco-home-lab"
media_stack_flaresolverr_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
media_stack_jellyfin_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
media_stack_jellyseerr_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
media_stack_qbittorrent_webui_password: "{{ vault_media_stack_qbittorrent_webui_password }}"
media_stack_prowlarr_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
media_stack_radarr_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
media_stack_sonarr_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
monitoring_nut_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
prometheus_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
prometheus_blackbox_exporter_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
qbittorrent_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
syncthing_user_interface_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
zigbee2mqtt_http_endpoint_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
mosquitto_server_fqdn: "raspberrypi2.{{ edge_environment_root_fqdn }}"
...
