---
volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  grafana:
    container_name: grafana
    depends_on:
      - prometheus
    image: grafana/grafana-oss:8.4.3
    environment:
      - GF_METRICS_ENABLED=true
    restart: on-failure
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.33.5
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
