---
volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  blackbox_exporter:
    container_name: blackbox-exporter
    command:
      - "--config.file=/etc/prometheus-blackbox-exporter/config.yaml"
    image: prom/blackbox-exporter:v0.20.0
    ports:
      - "9115:9115"
    restart: always
    volumes:
      - ./prometheus-blackbox-exporter-config.yaml:/etc/prometheus-blackbox-exporter/config.yaml

  grafana:
    container_name: grafana
    depends_on:
      - prometheus
    image: grafana/grafana-oss:8.5.0
    environment:
      - GF_METRICS_ENABLED=true
    restart: always
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
...
