---
backups_samba_share_path: "/media/data0/backups-marco"
configure_backup_restic: true
configure_asuswrt_chkwan: true
configure_docker: true
configure_home_assistant: true
configure_media_stack: true
configure_monitoring_backend: true
configure_mqtt_broker: true
configure_monitoring_nut: true
configure_monitoring_ont: true
configure_network_shares: true
configure_network_stack: true
configure_syncthing: true
configure_wifi: true
configure_zigbee2mqtt: true
disks_to_mount:
  - fstype: ext4
    opts: noatime
    path: /media/data0
    src: UUID=3fb762aa-c397-460b-809c-9ac741ce14f1
    state: mounted
has_argonone_case: true
has_coral_usb_accelerator: true
media_directory_path: "/media/data0/media"
monitoring_nut_server_admin_password: "{{ vault_raspberrypi2_monitoring_nut_server_admin_password }}"
monitoring_nut_server_admin_username: "{{ vault_raspberrypi2_monitoring_nut_server_admin_username }}"
monitoring_nut_devices:
  - id: eaton-ellipse-pro-1600-din-1
    description: Eaton Ellipse PRO 1600 DIN
    driver: usbhid-ups
    port: auto
    vendorId: "0463"
    productId: "FFFF"
    bus: "001"
restic_backup_repositories_default_path: "{{ backups_samba_share_path }}"
restic_backup_default_backup_job_repository_password: "{{ vault_workloads_backup_repository_password }}"
samba_shares:
  - comment: "Backups-Marco"
    create_mask: "0744"
    directory_group: "marco"
    directory_mask: "0755"
    directory_owner: "marco"
    force_group: "marco"
    force_user: "marco"
    name: "backups-marco"
    path: "{{ backups_samba_share_path }}"
    read_only: "yes"
    valid_users: "marco"
    write_list: "marco"
  - comment: "Media"
    create_mask: "0744"
    directory_group: users
    directory_mask: "0755"
    directory_owner: "{{ ansible_user }}"
    force_group: "users"
    force_user: "{{ ansible_user }}"
    name: "media"
    path: "{{ media_directory_path }}"
    read_only: "yes"
    valid_users: "@{{ samba_default_readers_group_name }}"
    write_list: "@{{ samba_default_writers_group_name }}"
samba_os_users:
  - append: true
    name: "{{ ansible_user }}"
    groups:
      - "{{ samba_default_readers_group_name }}"
      - "{{ samba_default_writers_group_name }}"
  - append: true
    name: "marco"
    groups:
      - "{{ samba_default_readers_group_name }}"
      - "{{ samba_default_writers_group_name }}"
tailscale_up_advertise_edge_environment_routes: true
zigbee_adapter_device_path: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220708144056-if00"

network_interfaces:
  - mac_address: "E4:5F:01:84:52:68"
    interface_name: eth0
    # Assigned using DHCP address reservation
    ipv4_address: "10.0.0.2"
...
