---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.crypto
  - name: community.docker
    version: "3.4.9"
  - name: community.general

roles:
  - name: geerlingguy.docker
    version: "7.0.1"
...
