---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.crypto
  - name: community.docker
    version: "3.10.3"
  - name: community.general
    version: "8.6.4"

roles:
  - name: geerlingguy.docker
    version: "7.1.0"
...
