---
collections:
  - name: ansible.posix
    version: "2.0.0"
  - name: ansible.utils
    version: "6.0.2"
  - name: community.crypto
    version: "3.1.1"
  - name: community.docker
    version: "5.2.0"
  - name: community.general
    version: "12.5.0"

roles:
  - name: geerlingguy.docker
    version: "8.0.0"
