---
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
  - directory: "config/pre-commit"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
  - directory: "/config/smart-desk/esphome"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
  - directory: "/docker/ansible"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/docker/ansible"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
  - directory: "/docker/ansible/etc/ansible/molecule"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
  - directory: "/docker/ansible/etc/ansible/roles/ferrarimarco_home_lab_node/files/config/sense-hat-exporter"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
  - directory: "/docker/ansible/etc/ansible/roles/ferrarimarco_home_lab_node/files/config/zte-f6005-ont-exporter"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
  - directory: "/docker/ansible/etc/ansible/roles/ferrarimarco_home_lab_node/files/config/dependency-updates-helper"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/docker/restic"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
version: 2
...
