---
version: 2
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/os-image-builder"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/cloud-init"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/template-renderer"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/config/smart-desk/esphome"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/docker/template-renderer"
    schedule:
      interval: "daily"
...
