---
updates:
  - package-ecosystem: "devcontainers"
    commit-message:
      prefix: "deps"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
  - directory: "/"
    commit-message:
      prefix: "deps"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    groups:
      dev-ci-tools:
        applies-to: version-updates
        patterns:
          - actions/*
          - docker/*
          - github/*
          - googleapis/*
          - ossf/scorecard-action
          - renovatebot/*
          - stefanzweifel/git-auto-commit-action
          - super-linter/super-linter
  - directories:
      - /config/ansible/roles/ferrarimarco_home_lab_node/files/config/monitoring-apt
      - /config/ansible/roles/ferrarimarco_home_lab_node/files/config/monitoring-ont
      - /config/ansible/roles/ferrarimarco_home_lab_node/files/config/sense-hat-exporter
      - /config/pre-commit
      - /config/smart-desk/esphome
      - /docker/ansible
      - /docker/ansible/molecule
    commit-message:
      prefix: "deps"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    groups:
      home-lab-workloads:
        applies-to: version-updates
        patterns:
          - esphome
          - prometheus-client
          - requests
      ci-cd-tooling:
        applies-to: version-updates
        patterns:
          - ansible
          - fqdn
          - molecule
          - molecule-plugins*
          - netaddr
          - pre-commit
          - paramiko
  - directories:
      - /config/ansible/roles/ferrarimarco_home_lab_node/files/config/dependency-updates-helper
      - /config/ansible/roles/ferrarimarco_home_lab_node/files/config/restic
      - /docker/ansible
      - /docker/ci-cd-tools
    commit-message:
      prefix: "deps"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    groups:
      home-lab-workloads:
        applies-to: version-updates
        patterns:
          - blakeblackshear/frigate
          - cadvisor/cadvisor
          - coredns/coredns
          - druggeri/nut_exporter
          - eclipse-mosquitto
          - fallenbagel/jellyseerr
          - flaresolverr/flaresolverr
          - grafana/grafana-oss
          - home-assistant/home-assistant
          - jellyfin/jellyfin
          - klutchell/unbound
          - koenkk/zigbee2mqtt
          - linuxserver/*
          - ngosang/restic-exporter
          - prom/blackbox-exporter
          - prom/prometheus
          - prometheus/node-exporter
          - restic/restic
          - syncthing/syncthing
          - traefik
      ci-cd-tooling:
        applies-to: version-updates
        patterns:
          - node
          - python
  - directories:
      - /docker/ci-cd-tools
    commit-message:
      prefix: "deps"
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    groups:
      dev-ci-tools:
        applies-to: version-updates
        patterns:
          - brace-expansion
          - release-please
version: 2
