---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/provisioning/docker/arm-image-builder"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/provisioning/terraform"
    schedule:
      interval: "daily"
