---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/provisioning/docker/arm-image-builder"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/provisioning/docker/iot-core-initializer"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/provisioning/terraform/environments/prod"
    schedule:
      interval: "daily"
