---
categories:
  - labels:
      - 'feature'
    title: '🚀 Features'
  - labels:
      - 'bugfix'
    title: '🐛 Bug Fixes'
  - labels:
      - 'dependencies'
      - 'documentation'
      - 'maintenance'
    title: '🧰 Maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  # Changelog

  $CHANGES

  See details of [all code changes](https://github.com/github/super-linter/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) since previous release
version-resolver:
  default: patch
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'dependencies'
      - 'feature'
  patch:
    labels:
      - 'bugfix'
      - 'documentation'
      - 'maintenance'
...
