---
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  # Changelog

  $CHANGES

  See details of [all code changes](https://github.com/github/super-linter/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) since previous release

categories:
  - title: '🚀  Features'
    labels:
      - 'feature'
  - title: '🐛  Bug Fixes'
    labels:
      - 'bugfix'
      - 'fix'
  - title: '🧰  Maintenance'
    labels:
      - 'dependencies'
      - 'documentation'
      - 'maintenance'
  - title: '🏎  Performance'
    label: 'performance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: dependencies'
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: documentation'
      - 'type: fix'
      - 'type: maintenance'
  default: patch
...
