---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.10.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.6.2"
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint-docker
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    - id: shellcheck
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.22
    hooks:
      - id: actionlint-docker
  - repo: https://github.com/psf/black
    rev: "22.12.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: "5.11.3"
    hooks:
      - id: isort
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.2
    hooks:
      - id: gitleaks-docker
...
