---
sudo: required

language: node_js

install:
  - sudo pip install -r requirements.txt
  - npm install

services:
  - docker

script:
  - yamllint --strict "$(git ls-files '*.yaml' '*.yml')"
  - markdownlint ./**/*.md
  - docker run --rm -i --name df-shellcheck -v "$(pwd)":/usr/src:ro ferrarimarco/shellcheck

matrix:
  fast_finish: true
