---
dist: bionic
jobs:
  fast_finish: true
  include:
    - name: "Linting"
      stage: linting
      language: shell
      cache:
        directories:
          - $HOME/.cache/pip
          - $GEM_HOME
          - vendor/bundle
          - $GOPATH/pkg/mod
          - $HOME/.nvm/versions
      install:
        - sudo scripts/linux/ci/install-dependencies.sh
        - scripts/linux/ci/install-node.sh
        - nvm use
        - scripts/linux/ci/install-linting-tools.sh
      script: |
        scripts/linux/ci/lint.sh || exit 1
    - name: "Build Smart Desk"
      stage: build
      language: shell
      install:
        - sudo scripts/linux/ci/install-dependencies.sh
      script: echo "build"
os: linux
services:
  - docker
stages:
  - linting
