---
dist: bionic
language: shell
os: linux
services:
  - docker
stages:
  - linting
jobs:
  fast_finish: true
  include:
    - name: "Linting"
      stage: linting
      language: shell
      cache:
        directories:
          - $HOME/.cache/pip
          - $GEM_HOME
          - vendor/bundle
          - $GOPATH/pkg/mod
          - $HOME/.nvm/versions
      install:
        - sudo scripts/linux/ci/install-dependencies.sh
        - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
        - scripts/linux/ci/install-node.sh
        - nvm use
        - scripts/linux/ci/install-linting-tools.sh
      script: |
        scripts/linux/ci/lint.sh || exit 1
    - name: "Build Smart Desk"
      stage: build
      language: shell
      env:
        - CMAKE_VERSION="3.17.3"
      cache:
        directories:
          - $HOME/.cache/pip
          - $GEM_HOME
          - vendor/bundle
          - $GOPATH/pkg/mod
          - $HOME/.nvm/versions
          - $HOME/.esp-idf
          - $HOME/.espressif/dist
          - $HOME/.espressif/tools
          - $HOME/cmake-$CMAKE_VERSION
      before_install:
        - sudo scripts/linux/ci/install-dependencies.sh "$CMAKE_VERSION"
      install:
        - sudo scripts/linux/ci/initialize-esp-idf.sh "$HOME/.esp-idf"
      script: |
        . "$HOME"/.esp-idf/export.sh;
        cd provisioning/esp32/smart_desk;
        idf.py build
      after_failure:
        - |
          scripts/linux/ci/diagnostics.sh --host
