---
sudo: required

language: node_js

install:
  - sudo pip install -r requirements.txt
  - npm install

node_js:
  - node

services:
  - docker

script:
  - yamllint --strict $(git ls-files '*.yaml' '*.yml')
  - find . -name "*js" ! -name "*node_modules*" | xargs markdownlint
  - docker run --rm -i --name df-shellcheck -v "$(pwd)":/usr/src:ro ferrarimarco/shellcheck

matrix:
  fast_finish: true
