---
sudo: required

language: shell

services:
  - docker

script:
 - find . -type f -iname "*.sh" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm koalaman/shellcheck:v0.4.7 "$line"; done

matrix:
  fast_finish: true
