---
sudo: required

language: shell

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - find . -name '*.sh' | xargs docker run -v $(pwd):/mnt --rm koalaman/shellcheck-alpine

matrix:
  fast_finish: true
