---
dist: bionic
jobs:
  fast_finish: true
  include:
    - name: "Linting"
      stage: linting
      language: shell
      cache:
        directories:
          - $HOME/.cache/pip
          - $GEM_HOME
          - vendor/bundle
          - $GOPATH/pkg/mod
          - $HOME/.nvm/versions
          - $HOME/.espressif/dist
          - $HOME/.espressif/tools
      install:
        - sudo scripts/linux/ci/install-dependencies.sh
        - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
        - scripts/linux/ci/install-node.sh
        - nvm use
        - scripts/linux/ci/install-linting-tools.sh
      script: |
        scripts/linux/ci/lint.sh || exit 1
    - name: "Build Smart Desk"
      stage: build
      language: shell
      cache:
        directories:
          - $HOME/.cache/pip
          - $GEM_HOME
          - vendor/bundle
          - $GOPATH/pkg/mod
          - $HOME/.nvm/versions
          - ./esp-idf
          - $HOME/.espressif/dist
          - $HOME/.espressif/tools
      before_install:
        - sudo scripts/linux/ci/install-dependencies.sh
      install:
        - sudo scripts/linux/ci/initialize-esp-idf.sh
      script: |
        echo "build"
os: linux
services:
  - docker
stages:
  - linting
