---
sudo: required

language: node_js

install:
  - sudo pip install -r requirements.txt
  - npm install

node_js:
  - node

services:
  - docker

script:
  - yamllint --strict $(git ls-files '*.yaml' '*.yml') || exit 1
  - >
    find -name "*.md" -not -path "*/node_modules/*"
    | xargs markdownlint
    || exit 1
  - find . -type f -iname "*.sh" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm koalaman/shellcheck:v0.7.0 "$line" || exit 1; done;

matrix:
  fast_finish: true
