---
extends: default

rules:
  colons:
    max-spaces-after: 1
  comments: enable
    level: error
  comments-indentation: enable
    level: error
  document-end: enable
  document-start:
    level: error
  empty-values: enable
  key-ordering: enable
  line-length:
    max: 200
    allow-non-breakable-inline-mappings: true
  octal-values: enable
  quoted-strings: disable
  truthy:
    level: error
