---
extends: default

rules:
  colons:
    max-spaces-after: 1
  comments:
    level: error
    # cloud-init expects the first line to be #cloud-config and this conflicts with
    # the rules.comments.require-starting-space directive.
    # See https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments
    ignore: |
      **/cloud-init*/**/user-data.yaml
  comments-indentation:
    level: error
  document-end:
    level: error
  document-start:
    level: error
  empty-values: enable
  line-length:
    max: 250
    allow-non-breakable-inline-mappings: true
  octal-values: enable
  truthy:
    # because the "on" key in GitHub actions workflow configuration files
    check-keys: false
    level: error
...
