---
extends: default

rules:
  colons:
    max-spaces-after: 1
  comments:
    level: error
  comments-indentation:
    level: error
  document-start:
    level: error
  empty-values: enable
  line-length:
    max: 250
    allow-non-breakable-inline-mappings: true
  octal-values: enable
  truthy:
    level: error
