---
options:
    env:
        - TF_INPUT=false
steps:
    # - id: 'super-linter'
    #   name: "github/super-linter:v3.6.0"
    #   env:
    #     - ACTIONS_RUNNER_DEBUG=true
    #     - ANSIBLE_DIRECTORY=configuration/ansible
    #     - DEFAULT_WORKSPACE=/workspace
    #     - DISABLE_ERRORS=false
    #     - LINTER_RULES_PATH=/workspace
    #     # Disable multiple status reporting to avoid reporting any status
    #     # (see the if condition in super-linter/lib/linter.sh)
    #     - MULTI_STATUS=false
    #     - RUN_LOCAL=true
    #     - VALIDATE_ALL_CODEBASE=true
    #     - VALIDATE_ANSIBLE=true
    #     - VALIDATE_BASH=true
    #     - VALIDATE_DOCKER=true
    #     - VALIDATE_DOCKER_HADOLINT=true
    #     - VALIDATE_EDITORCONFIG=true
    #     - VALIDATE_JSON=true
    #     - VALIDATE_MD=true
    #     - VALIDATE_TERRAFORM=true
    #     - VALIDATE_TERRAFORM_TERRASCAN=true
    #     - VALIDATE_YAML=true
    - id: 'clone repository'
      name: gcr.io/cloud-builders/git
      args: ['clone', 'https://github.com/ferrarimarco/home-lab.git']
    - id: 'provision infrastructure'
      name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
      - '-c'
      - |
        echo "Saving eventual failures log to: ${_FAILURE_FILE_PATH}"

        scripts/submit-cloud-build.sh \
          --cloud-build-substitutions "BRANCH_NAME=$BRANCH_NAME" \
          --commit-sha "$COMMIT_SHA" \
          --destination-directory-path "provisioning/terraform" \
          --failure-file-path "${_FAILURE_FILE_PATH}" \
          --git-repository-path "home-lab"

        # Check if there is any failure.
        if [ -s "${_FAILURE_FILE_PATH}" ]; then
            echo
            echo "Some builds failed:"
            cat "${_FAILURE_FILE_PATH}"
            echo "Exiting."
            exit 1
        else
            echo "Build succeeded."
        fi
    - id: 'start other build jobs'
      name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
      - '-c'
      - |
        echo "Saving eventual failures log to: ${_FAILURE_FILE_PATH}"

        scripts/submit-cloud-build.sh \
          --cloud-build-substitutions "COMMIT_SHA=$COMMIT_SHA,BRANCH_NAME=$BRANCH_NAME,TAG_NAME=$TAG_NAME" \
          --commit-sha "$COMMIT_SHA" \
          --destination-directory-path "provisioning/esp32/smart_desk" \
          --failure-file-path "${_FAILURE_FILE_PATH}" \
          --git-repository-path "home-lab" \
          &

        scripts/submit-cloud-build.sh \
          --cloud-build-substitutions "_DOCKER_IMAGE_ID=arm-image-builder,_DOCKER_IMAGE_TAG=$SHORT_SHA" \
          --commit-sha "$COMMIT_SHA" \
          --destination-directory-path "provisioning/docker/arm-image-builder" \
          --failure-file-path "${_FAILURE_FILE_PATH}" \
          --git-repository-path "home-lab" \
          &

        scripts/submit-cloud-build.sh \
          --commit-sha "$COMMIT_SHA" \
          --destination-directory-path "provisioning/arm/beaglebone-black" \
          --failure-file-path "${_FAILURE_FILE_PATH}" \
          --git-repository-path "home-lab" \
          &

        wait

        # Check if there is any failure.
        if [ -s "${_FAILURE_FILE_PATH}" ]; then
            echo
            echo "Some builds failed:"
            cat "${_FAILURE_FILE_PATH}"
            echo "Exiting."
            exit 1
        else
            echo "Build succeeded."
        fi
substitutions:
  _FAILURE_FILE_PATH: './failure.log'
tags: ['$PROJECT_ID', '$BUILD_ID', '$_PR_NUMBER', '$REPO_NAME', '$COMMIT_SHA', '$SHORT_SHA', '$BRANCH_NAME', '$TAG_NAME']
