---
options:
    env:
        - TF_INPUT=false
steps:
    - id: 'branch name'
      name: 'alpine'
      entrypoint: 'sh'
      args:
          - '-c'
          - |
            echo "***********************"
            echo "Branch: $BRANCH_NAME"
            echo "***********************"
    - id: 'decrypt secrets'
      name: gcr.io/cloud-builders/gcloud
      entrypoint: 'sh'
      args:
          - '-c'
          - |
            cd $_TERRAFORM_ENVIRONMENT_PATH || exit 1
            /builder/google-cloud-sdk/bin/gcloud \
                kms decrypt \
                --ciphertext-file=terraform.tfvars.enc \
                --plaintext-file=terraform.tfvars \
                --location=global \
                --keyring=cloud-build-keyring \
                --key=cloudbuild-crypto-key
    - id: 'tf init'
      name: 'hashicorp/terraform:0.12.20'
      entrypoint: 'sh'
      args:
          - '-c'
          - |
            cd $_TERRAFORM_ENVIRONMENT_PATH || exit 1
            terraform init || exit 1
            cd ../../
    - id: 'tf validate'
      name: 'hashicorp/terraform:0.12.20'
      entrypoint: 'sh'
      args:
          - '-c'
          - |
            cd $_TERRAFORM_ENVIRONMENT_PATH || exit 1
            terraform validate || exit 1
            cd ../../
    - id: 'tf plan'
      name: 'hashicorp/terraform:0.12.20'
      entrypoint: 'sh'
      args:
          - '-c'
          - |
            cd $_TERRAFORM_ENVIRONMENT_PATH || exit 1
            terraform plan
    - id: 'tf apply'
      name: 'hashicorp/terraform:0.12.20'
      entrypoint: 'sh'
      args:
          - '-c'
          - |
            if [ "${BRANCH_NAME}" = "master" ]; then
                cd $_TERRAFORM_ENVIRONMENT_PATH || exit 1
                echo $BRANCH_NAME
                terraform apply -auto-approve || exit 1
            else
                echo "Not applying any Terraform change. Not on master branch."
                echo "Current branch: $BRANCH_NAME"
            fi
    - id: 'esp-idf build'
      name: 'espressif/idf:$_ESP_IDF_VERSION_IMAGE_TAG'
      args:
          - |
            cd $_ESP_SMART_DESK_PATH && idf.py build
substitutions:
    _ESP_IDF_VERSION_IMAGE_TAG: 'release-v4.2'
    _ESP_SMART_DESK_PATH: '/workspace/provisioning/esp32/smart_desk'
    _TERRAFORM_ENVIRONMENT_PATH: '/workspace/provisioning/terraform/environments/prod'
