---
galaxy_info:
  author: https://github.com/ferrarimarco
  description: Role to configure Home Lab nodes
  license: MIT
  min_ansible_version: "2.13"
  platforms:
    - name: Debian
      versions:
        - all
...
