steps:
- name: 'hashicorp/consul-template:0.25.1-alpine'
  args: [ '/bin/consul-template', '-h' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_ID', '.' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'tag', 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_ID', 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_ID:$_DOCKER_IMAGE_TAG' ]
# images:
#   - 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_ID:$_DOCKER_IMAGE_TAG'
