options:
  machineType: 'N1_HIGHCPU_8'
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:$_CLOUD_SDK_IMAGE_TAG'
  entrypoint: gsutil
  args: ['-m', 'cp', '-r', 'gs://${PROJECT_ID}-configuration/terraform/$_TERRAFORM_ENVIRONMENT_PATH/consul-template', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:$_CLOUD_SDK_IMAGE_TAG'
  entrypoint: 'sh'
  # See https://github.com/hashicorp/consul-template#docker-image-use
  args:
      - '-c'
      - |
        echo "Contents of $(pwd): $(ls -al)"
        echo "Creating the consul-template user"
        addgroup -g 1000 consul-template && \
        adduser -u 100 -S -G consul-template consul-template
        mkdir -p $_RENDERED_TEMPLATES_PATH
        chown consul-template:consul-template $_RENDERED_TEMPLATES_PATH
- name: 'hashicorp/consul-template:$_CONSUL_TEMPLATE_IMAGE_TAG'
  args:
    - '/bin/consul-template'
    - '-config'
    - 'consul-template/config.hcl'
    - '-once'
    - '-template'
    - 'templates/etc/mosquitto/mosquitto:$_RENDERED_TEMPLATES_PATH/etc/mosquitto/mosquitto_pub'
    - '-template'
    - 'templates/etc/mosquitto/mosquitto:$_RENDERED_TEMPLATES_PATH/etc/mosquitto/mosquitto_sub'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--privileged', 'gcr.io/$PROJECT_ID/arm-image-builder:$_ARM_BUILDER_IMAGE_TAG']
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'create', '--name', '$_DOCKER_BUILDX_BUILDER_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'use', '$_DOCKER_BUILDX_BUILDER_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'inspect', '--bootstrap']
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '-t', 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_ID:$_DOCKER_IMAGE_TAG', '--build-arg', 'CONFIGURATION_DIRECTORY_PATH=$_RENDERED_TEMPLATES_PATH', '--push', '.']
options:
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'
substitutions:
  _ARM_BUILDER_IMAGE_TAG: '4a17db0'
  _CLOUD_SDK_IMAGE_TAG: 'alpine'
  _CONSUL_TEMPLATE_IMAGE_TAG: '0.25.1-alpine'
  _DOCKER_BUILDX_BUILDER_NAME: 'multiarch_builder'
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm/v7,linux/arm64'
  _RENDERED_TEMPLATES_PATH: './rendered-templates'
timeout: 37000s
