---
- name: Ensure required apt packages are installed
  apt:
    cache_valid_time: 3600
    pkg: ['connman']
    state: present
    update_cache: true

- name: Enable the connman service
  service:
    name: connman
    enabled: true

- name: Configure network interfaces with /etc/network/interfaces
  template:
    backup: false
    dest: /etc/network/interfaces
    group: root
    mode: 0644
    owner: root
    src: templates/etc/network/interfaces.j2

- name: Create the connman configuration directory
  file:
    group: root
    mode: 0755
    owner: root
    path: /etc/connman
    state: directory

- name: Generate the main connman configuration file
  template:
    backup: false
    dest: /etc/connman/main.cfg
    group: root
    mode: 0644
    owner: root
    src: templates/etc/connman/main.cfg.j2

- name: Create the connman service configuration directory
  file:
    group: root
    mode: 0755
    owner: root
    path: /var/lib/connman
    state: directory

- name: Generate connman service configuration files
  template:
    backup: false
    dest: /var/lib/connman/ethernet.config
    group: root
    mode: 0644
    owner: root
    src: templates/var/lib/connman/ethernet.config.j2
  notify: restart_connman
