---
- name: Create the private key directory
  file:
    group: root
    mode: 0700
    owner: root
    path: "{{ google_cloud_iot_core.private_key_path | dirname }}"
    state: directory

- name: Create the public key directory
  file:
    group: root
    mode: 0700
    owner: root
    path: "{{ google_cloud_iot_core.public_key_path | dirname }}"
    state: directory

- name: Generate an OpenSSL private key to register the device
  openssl_privatekey:
    curve: "{{ google_cloud_iot_core.private_key_curve }}"
    path: "{{ google_cloud_iot_core.private_key_path }}"
    size: "{{ google_cloud_iot_core.private_key_size }}"

- name: Generate an OpenSSL public key to register the device
  openssl_publickey:
    path: "{{ google_cloud_iot_core.public_key_path }}"
    privatekey_path: "{{ google_cloud_iot_core.private_key_path }}"
