---
- name: Run OS-family specific tasks
  include_tasks: "{{ ferrarimarco_home_lab_node_os_item }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}.yaml"
  loop: "{{ q('first_found', params, errors='ignore') }}"
  loop_control:
    loop_var: ferrarimarco_home_lab_node_os_item

- name: Configure the BeagleBone Black (if applicable)
  include_tasks: "beaglebone-black.yaml"
  when: beaglebone_black is defined

- name: Generate credentials for Google Cloud IoT Core
  include_tasks: "cloud-iot-core.yaml"
  when: google_cloud_iot_core_device
