---
dependency:
  name: galaxy
  requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: /etc/ansible/playbooks/main.yaml
...
