---
version: "3"
services:
  dnsmasq:
    deploy:
      replicas: 1
    image: ferrarimarco/home-lab-dnsmasq:dev-latest
    network_mode: "host"
  pxe:
    deploy:
      replicas: 1
    image: ferrarimarco/home-lab-pxe:dev-latest
    network_mode: "host"
