---
- name: Import the bootstrap playbook
  ansible.builtin.import_playbook: bootstrap.yaml

- name: Configure container engine
  hosts: all
  gather_facts: true
  roles:
    - role: geerlingguy.docker
      become: true
