---
- name: Import the boot bare metal playbook
  ansible.builtin.import_playbook: boot-bare-metal.yaml

- name: Import the bootstrap playbook
  ansible.builtin.import_playbook: bootstrap.yaml

- name: Import the container engine playbook
  ansible.builtin.import_playbook: container-engine.yaml

- name: Import the proxmox node playbook
  ansible.builtin.import_playbook: proxmox-node.yaml

- name: Import the home lab node playbook
  ansible.builtin.import_playbook: home-lab-node.yaml
