---
- name: Import the bootstrap playbook
  ansible.builtin.import_playbook: bootstrap.yaml

- name: Configure Home Lab nodes
  hosts: all
  gather_facts: true
  roles:
    - role: geerlingguy.docker
      become: true
    - role: ferrarimarco_home_lab_node
...
