---
- name: Import the bootstrap playbook
  ansible.builtin.import_playbook: bootstrap.yaml

- name: Import the container engine playbook
  ansible.builtin.import_playbook: container-engine.yaml

- name: Configure Home Lab nodes
  hosts: "{{ home_lab_hosts | default('all') }}"
  gather_facts: true
  roles:
    - role: ferrarimarco_home_lab_node
...
