---
- name: Import the bootstrap playbook
  ansible.builtin.import_playbook: bootstrap.yaml

- name: Configure Proxmox nodes
  hosts: home_lab_proxmox_nodes
  gather_facts: true
  roles:
    - role: ferrarimarco_home_lab_proxmox
