#cloud-config
---
chpasswd:
  expire: true
  list:
    - ubuntu:ubuntu

groups:
  - microk8s

growpart:
  mode: auto
  devices: ["/"]
  ignore_growroot_disabled: false

locale: "en_US.UTF-8"

# update the contents of /etc/hosts based on the hostname/fqdn specified
manage_etc_hosts: true

# Set up the NTP client with default configuration and client
ntp:
  enabled: true
  ntp_client: auto

package_update: true
package_upgrade: true
package_reboot_if_required: true

random_seed:
  file: /dev/urandom
  command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
  command_required: true

resize_rootfs: true

snap:
  commands:
    "001": "snap install microk8s --classic --channel=1.21/stable"
    "002": "/snap/bin/microk8s status --wait-ready"
    "003": "/snap/bin/microk8s enable dns ingress metallb:10.254.0.0/16 storage"
    "004": "/snap/bin/microk8s status --wait-ready"

# Disable password authentication with the SSH daemon
# for the default user
ssh_pwauth: false

# Remove default host keys if any
ssh_deletekeys: true

timezone: "Etc/UTC"

users:
  - default
  - name: marco
    groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, microk8s, netdev, plugdev, sudo, video]
    lock_passwd: true
    shell: /usr/bin/bash
    ssh_import_id: gh:ferrarimarco
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
...
