---
ansible_connection: winrm
ansible_port: 5986

# The following is necessary for Python 2.7.9+ (or any older Python that has
# backported SSLContext, eg, Python 2.7.5 on RHEL7) when using default WinRM
# self-signed certificates:
ansible_winrm_server_cert_validation: ignore
