---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO}"
    pre_build_image: true
provisioner:
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  inventory:
    host_vars:
      instance:
        ansible_user: root
  name: ansible
  playbooks:
    converge: converge.yaml
verifier:
  name: ansible
...
