---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO}"
    pre_build_image: true
provisioner:
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yaml}
verifier:
  name: ansible
...
