---
- name: Ensure /etc/docker/ directory exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"
  when: docker_daemon_options.keys() | length > 0

- name: Configure Docker daemon options
  ansible.builtin.copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: "0644"
  notify: restart docker
  when: docker_daemon_options.keys() | length > 0

- name: Ensure Docker is started and enabled at boot
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: true

- name: Include docker-compose tasks
  ansible.builtin.include_tasks: docker-compose.yml
  when: docker_install_compose

- name: Ensure docker users are added to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
...
