---
- name: Copy fail2ban custom configuration file into place
  notify: restart fail2ban
  ansible.builtin.template:
    src: "{{ security_fail2ban_custom_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"

- name: Ensure fail2ban is running and enabled on boot
  ansible.builtin.service:
    name: "{{ fail2ban_service_name }}"
    state: started
    enabled: true
...
