---
- name: Load a variable file based on the OS type, or a default if not found.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - "default.yaml"

- name: Load Raspberry Pi OS variables.
  ansible.builtin.include_vars: "raspberry-pi-os.yaml"
  when: is_raspberry_pi

- name: Add Sense Hat packages to the list of packages to install
  ansible.builtin.set_fact:
    apt_packages_to_install: "{{ apt_packages_to_install + raspberry_pi_sense_hat_apt_packages }}"
  when: has_sense_hat

- name: Add fail2ban packages to the list of packages to install
  ansible.builtin.set_fact:
    apt_packages_to_install: "{{ apt_packages_to_install + fail2ban_packages }}"
  when: security_fail2ban_enabled

- name: Add unattended-upgrades packages to the list of packages to install
  ansible.builtin.set_fact:
    apt_packages_to_install: "{{ apt_packages_to_install + unattended_upgrades_packages }}"
  when: security_unattended_upgrades_enabled
...
