---
- name: Load a variable file based on the OS type, or a default if not found.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - "default.yaml"

- name: Load Raspberry Pi OS variables.
  ansible.builtin.include_vars: "raspberry-pi-os.yaml"
  when: is_raspberry_pi

- name: Register facts based on the OS type, or a default if not found
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - "register-{{ ansible_distribution }}-{{ ansible_distribution_version }}-facts.yaml"
    - "register-{{ ansible_distribution }}-facts.yaml"
    - "register-{{ ansible_os_family }}-facts.yaml"
    - "register-default-facts.yaml"

- name: Include SSH tasks
  ansible.builtin.include_tasks:
    file: register-ssh-facts.yaml

- name: Include Raspberry Pi Sense Hat tasks
  ansible.builtin.include_tasks:
    file: register-raspberry-pi-sense-hat-facts.yaml
  when: has_sense_hat

- name: Include Docker tasks
  ansible.builtin.include_tasks:
    file: register-docker-facts.yaml
  when: configure_docker

- name: Include fail2ban tasks
  ansible.builtin.include_tasks:
    file: register-fail2ban-facts.yaml
  when: security_fail2ban_enabled

- name: Include unattended-upgrades tasks
  ansible.builtin.include_tasks:
    file: register-unattended-upgrades-facts.yaml
  when: security_unattended_upgrades_enabled

- name: Include monitoring tasks
  ansible.builtin.include_tasks:
    file: register-monitoring-facts.yaml
  when: configure_monitoring

- name: Include monitoring backend tasks
  ansible.builtin.include_tasks:
    file: register-monitoring-backend-facts.yaml
  when: configure_monitoring_backend
...
