---
- name: Initialize the list of OS services to restart
  # For item.item, see https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#registering-variables-with-a-loop
  # "When you use register with a loop, the data structure placed in the variable will contain a results attribute
  # that is a list of all responses from the module. This differs from the data structure returned when using register without a loop."
  ansible.builtin.set_fact:
    os_services_to_restart: "{{ os_services_to_restart + item.item.os_services_to_restart }}"
  when: item.changed and item.item.os_services_to_restart is defined
  with_items: "{{ system_wide_copied_configuration_directories.results | default([]) + system_wide_rendered_templates.results | default([]) }}"

- name: Restart OS services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
  with_items: "{{ os_services_to_restart | unique }}"

- name: Pull container images
  debugger: on_failed
  changed_when: '"Pull complete" in docker_compose_pull_result.stdout or "Pull complete" in docker_compose_pull_result.stderr'
  ansible.builtin.command: >
    docker compose \
    --file {{ item.compose_file_path }} \
    pull \
    --include-deps
  register: docker_compose_pull_result
  when: item.pull_container_images
  with_items: "{{ docker_compose_up_items | unique }}"

- name: Start Docker Compose services
  debugger: on_failed
  changed_when: '"Started" in docker_compose_up_result.stdout or "Started" in docker_compose_up_result.stderr'
  ansible.builtin.command: >
    docker compose \
    --file {{ item.compose_file_path }} \
    up \
    --build \
    --detach \
    --remove-orphans
  register: docker_compose_up_result
  when: item.start_containerized_service
  with_items: "{{ docker_compose_up_items | unique }}"

- name: Initialize the list of Docker Compose services to restart
  ansible.builtin.set_fact:
    docker_compose_services_to_restart: "{{ docker_compose_services_to_restart + item.item.docker_compose_services_to_restart }}"
  when: item.changed and item.item.docker_compose_services_to_restart is defined
  with_items: "{{ system_wide_copied_configuration_directories.results | default([]) + system_wide_rendered_templates.results | default([]) }}"

- name: Restart Docker Compose services
  changed_when: '"Started" in docker_compose_restart_result.stdout or "Started" in docker_compose_restart_result.stderr'
  ansible.builtin.command: >
    docker compose \
    --file {{ item.compose_file_path }} \
    restart
  register: docker_compose_restart_result
  with_items: "{{ docker_compose_services_to_restart | unique }}"
...
