---
- name: Setup variables
  ansible.builtin.import_tasks: include-variables.yaml

- name: Include users setup tasks
  ansible.builtin.include_tasks:
    file: users.yaml
    apply:
      become: true

- name: Include Debian tasks
  ansible.builtin.include_tasks: setup-Debian.yaml
  when: ansible_facts.os_family == 'Debian'

- name: Include Systemd tasks
  ansible.builtin.include_tasks:
    file: setup-systemd.yaml
    apply:
      become: true

- name: Include SSH tasks
  ansible.builtin.include_tasks:
    file: ssh.yaml
    apply:
      become: true

- name: Include Raspberry Pi tasks
  ansible.builtin.include_tasks: setup-raspberry-pi.yaml
  when: is_raspberry_pi

- name: Include fail2ban tasks
  ansible.builtin.include_tasks:
    file: fail2ban.yaml
    apply:
      become: true
  when: security_fail2ban_enabled

- name: Include unattended-upgrades tasks
  ansible.builtin.include_tasks:
    file: unattended-upgrades.yaml
    apply:
      become: true
  when: security_unattended_upgrades_enabled

- name: Include wifi tasks
  ansible.builtin.include_tasks:
    file: wifi.yaml
    apply:
      become: true
  when: configure_wifi

- name: Include Docker tasks
  ansible.builtin.include_tasks:
    file: docker.yaml
    apply:
      become: true
  when: configure_docker

- name: Include docker-compose tasks
  ansible.builtin.include_tasks:
    file: setup-compose.yaml
    apply:
      become: true
  when: configure_docker_compose
...
