---
- name: Setup variables
  ansible.builtin.import_tasks: include-variables.yaml

- name: Set the ownership of system-wide configuration directories
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: "{{ item }}"
  become: true
  with_items: "{{ directories_to_ensure_ownership }}"

- name: Create system-wide configuration directories
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: "{{ item }}"
    state: directory
  become: true
  with_items: "{{ configuration_directories_to_create }}"

- name: Copy configuration directories
  ansible.builtin.copy:
    src: "{{ item.src }}/"
    dest: "{{ item.dest }}/"
    group: root
    directory_mode: "0755"
    mode: "0644"
    owner: root
  become: true
  register: system_wide_copied_configuration_directories
  with_items: "{{ configuration_directories_to_copy }}"

- name: Copy system-wide, templated configuration files in place
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  become: true
  register: system_wide_rendered_templates
  with_items: "{{ templates_to_render }}"

- name: Download files
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  register: system_wide_downloaded_files
  with_items: "{{ files_to_download }}"

- name: Include users setup tasks
  ansible.builtin.include_tasks:
    file: users.yaml
    apply:
      become: true

- name: Include Debian tasks
  ansible.builtin.include_tasks: setup-Debian.yaml
  when: ansible_facts.os_family == 'Debian'

- name: Include Systemd tasks
  ansible.builtin.include_tasks:
    file: setup-systemd.yaml
    apply:
      become: true

- name: Include SSH tasks
  ansible.builtin.include_tasks:
    file: ssh.yaml
    apply:
      become: true

- name: Include Raspberry Pi tasks
  ansible.builtin.include_tasks: setup-raspberry-pi.yaml
  when: is_raspberry_pi

- name: Include wifi tasks
  ansible.builtin.include_tasks:
    file: wifi.yaml
    apply:
      become: true
  when: configure_wifi

- name: Include Docker tasks
  ansible.builtin.include_tasks:
    file: docker.yaml
    apply:
      become: true
  when: configure_docker

- name: Include OS services tasks
  ansible.builtin.include_tasks:
    file: os-services.yaml
    apply:
      become: true

- name: Include disk setup tasks
  ansible.builtin.include_tasks:
    file: setup-disks.yaml
    apply:
      become: true

- name: Include docker-compose tasks
  ansible.builtin.include_tasks:
    file: setup-compose.yaml
    apply:
      become: true
  when: configure_docker_compose

- name: Include Argon One case tasks
  ansible.builtin.include_tasks:
    file: setup-argonone-case.yaml
    apply:
      become: true
  when: has_argonone_case

- name: Include invoke handlers for system-wide configuration
  ansible.builtin.include_tasks:
    file: invoke-system-wide-configuration-handlers.yaml
    apply:
      become: true
...
