---
- name: Configure OS services
  ansible.builtin.service:
    name: "{{ item.service_name }}"
    state: "{{ item.service_state }}"
    enabled: "{{ item.enabled }}"
  with_items: "{{ os_services_to_configure }}"
...
