---
- name: Add {{ fact_category }} OS repositories to the list of OS repositories to add
  ansible.builtin.set_fact:
    apt_repositories_to_add: "{{ apt_repositories_to_add + fact_os_package_repositories_to_add }}"

- name: Add {{ fact_category }} configuration directories to the list of configuration directories to create
  ansible.builtin.set_fact:
    configuration_directories_to_create: "{{ configuration_directories_to_create + fact_configuration_directories_to_create }}"

- name: Add {{ fact_category }} configuration directories to the list of configuration directories to copy
  ansible.builtin.set_fact:
    configuration_directories_to_copy: "{{ configuration_directories_to_copy + fact_configuration_directories_to_copy }}"

- name: Add {{ fact_category }} OS packages to the list of OS packages to install
  ansible.builtin.set_fact:
    apt_packages_to_install: "{{ apt_packages_to_install + fact_os_packages_to_install }}"

- name: Add {{ fact_category }} OS packages to the list of OS packages to install
  ansible.builtin.set_fact:
    deb_packages_to_install: "{{ deb_packages_to_install + fact_deb_packages_to_install }}"

- name: Add {{ fact_category }} OS packages to uninstall to the list of OS packages to uninstall
  ansible.builtin.set_fact:
    apt_packages_to_uninstall: "{{ apt_packages_to_uninstall + fact_os_packages_to_uninstall }}"

- name: Add {{ fact_category }} OS services to configure to the list of OS services to configure
  ansible.builtin.set_fact:
    os_services_to_configure: "{{ os_services_to_configure + fact_os_services_to_configure }}"

- name: Add {{ fact_category }} templates to render items to the list of templates to render
  ansible.builtin.set_fact:
    templates_to_render: "{{ templates_to_render + fact_templates_to_render }}"

- name: Add {{ fact_category }} Docker Compose up items to the list of Docker Compose up items
  ansible.builtin.set_fact:
    docker_compose_up_items: "{{ docker_compose_up_items + fact_docker_compose_up_items }}"

- name: Add {{ fact_category }} files to download to the list of files to download
  ansible.builtin.set_fact:
    files_to_download: "{{ files_to_download + fact_files_to_download }}"
...
