---
- name: Add fail2ban packages to the list of packages to install
  ansible.builtin.set_fact:
    apt_packages_to_install: "{{ apt_packages_to_install + fail2ban_packages }}"

- name: Add fail2ban services to configure to the list of services to configure
  ansible.builtin.set_fact:
    os_services_to_configure: "{{ os_services_to_configure + fail2ban_os_services_to_configure }}"
...
