---
- name: Add all hosts to the list of DNS A records to check
  ansible.builtin.set_fact:
    monitoring_backend_dns_records_to_check: "{{ monitoring_backend_dns_records_to_check + monitoring_backend_dns_a_record_check_template_for_ansible_hosts }}"
  with_items: "{{ groups['all'] }}"

- name: Add the DNS records defined for this and other hosts to the list of DNS records to check
  ansible.builtin.set_fact:
    monitoring_backend_dns_records_to_check: "{{ monitoring_backend_dns_records_to_check + monitoring_backend_dns_record_check_template }}"
  with_items: "{{ dns_records_to_configure }}"

- name: Add the edge DNS servers to the list of DNS records to check
  ansible.builtin.set_fact:
    monitoring_backend_dns_records_to_check: "{{ monitoring_backend_dns_records_to_check + monitoring_backend_dns_record_check_template }}"
  with_items:
    - source: "{{ edge_dns_server.fqdn }}"
      query_type: "A"

- name: Remove duplicates from the list of DNS records to check
  ansible.builtin.set_fact:
    monitoring_backend_dns_records_to_check: "{{ monitoring_backend_dns_records_to_check | unique }}"

- name: Debug monitoring_backend_dns_records_to_check
  ansible.builtin.debug:
    var: monitoring_backend_dns_records_to_check
    verbosity: 1

- name: Add all Prometheus Node Exporter endpoints to the list of HTTP endpoints to check
  ansible.builtin.set_fact:
    monitoring_backend_http_endpoints_to_check: "{{ monitoring_backend_http_endpoints_to_check + monitoring_backend_http_prometheus_node_exporter_endpoint_check_template }}"
  with_items: "{{ groups['all'] }}"

- name: Add all cAdvisor endpoints to the list of HTTP endpoints to check
  ansible.builtin.set_fact:
    monitoring_backend_http_endpoints_to_check: "{{ monitoring_backend_http_endpoints_to_check + monitoring_backend_http_cadvisor_endpoint_check_template }}"
  when: hostvars[item].configure_docker
  with_items: "{{ groups['all'] }}"

- name: Debug monitoring_backend_http_endpoints_to_check
  ansible.builtin.debug:
    var: monitoring_backend_http_endpoints_to_check
    verbosity: 1

- name: Add upstream DNS servers to the list of hosts to check via ICMP
  ansible.builtin.set_fact:
    monitoring_backend_icmp_ping_hosts_to_check: "{{ monitoring_backend_icmp_ping_hosts_to_check + upstream_dns_servers }}"

- name: Sort the list of hosts to check via ICMP
  ansible.builtin.set_fact:
    monitoring_backend_icmp_ping_hosts_to_check: "{{ monitoring_backend_icmp_ping_hosts_to_check | unique | sort }}"

- name: Debug monitoring_backend_icmp_ping_hosts_to_check
  ansible.builtin.debug:
    var: monitoring_backend_icmp_ping_hosts_to_check
    verbosity: 1
...
