---
- name: Debug fact_docker_compose_up_items for {{ fact_category }}
  ansible.builtin.debug:
    var: fact_docker_compose_up_items
    verbosity: 1

- name: Initialize the start containerized services flag list for {{ fact_category }}
  ansible.builtin.set_fact:
    fact_docker_compose_up_items_with_start_flag: []

- name: Configure the start containerized services flag for {{ fact_category }}
  ansible.builtin.set_fact:
    fact_docker_compose_up_items_with_start_flag: "{{ fact_docker_compose_up_items_with_start_flag + [fact_docker_compose_up_items_with_start_flag_item | combine({'start_containerized_service': fact_start_containerized_services})] }}"
  with_items: "{{ fact_docker_compose_up_items }}"
  loop_control:
    loop_var: fact_docker_compose_up_items_with_start_flag_item

- name: Debug fact_docker_compose_up_items_with_start_flag for {{ fact_category }}
  ansible.builtin.debug:
    var: fact_docker_compose_up_items_with_start_flag
    verbosity: 1

- name: Register facts for {{ fact_category }}
  ansible.builtin.set_fact:
    apt_packages_to_install: "{{ apt_packages_to_install + fact_os_packages_to_install }}"
    apt_packages_to_uninstall: "{{ apt_packages_to_uninstall + fact_os_packages_to_uninstall }}"
    apt_repositories_to_add: "{{ apt_repositories_to_add + fact_os_package_repositories_to_add }}"
    dns_records_to_configure: "{{ dns_records_to_configure + fact_dns_records_to_configure }}"
    configuration_directories_to_copy: "{{ configuration_directories_to_copy + fact_configuration_directories_to_copy }}"
    configuration_directories_to_create: "{{ configuration_directories_to_create + fact_configuration_directories_to_create }}"
    cron_jobs: "{{ cron_jobs + fact_cron_jobs }}"
    deb_packages_to_install: "{{ deb_packages_to_install + fact_deb_packages_to_install }}"
    docker_compose_up_items: "{{ docker_compose_up_items + fact_docker_compose_up_items_with_start_flag }}"
    files_to_download: "{{ files_to_download + fact_files_to_download }}"
    files_to_remove: "{{ files_to_remove + fact_files_to_remove }}"
    os_groups_to_create: "{{ os_groups_to_create + fact_os_groups_to_create }}"
    os_services_to_configure: "{{ os_services_to_configure + fact_os_services_to_configure }}"
    os_users_to_create: "{{ os_users_to_create + fact_os_users_to_create }}"
    templates_to_render: "{{ templates_to_render + fact_templates_to_render }}"
...
