---
- name: Add monitoring configuration directories to the list of configuration directories to create
  ansible.builtin.set_fact:
    configuration_directories_to_create: "{{ configuration_directories_to_create + monitoring_configuration_directories }}"
...
