---
# These setup facts are needed regardless of the flag to enable or disable a given stack
- name: Register setup facts for {{ fact_category }}
  ansible.builtin.set_fact:
    apt_packages: "{{ apt_packages + fact_os_packages }}"
    apt_repositories: "{{ apt_repositories + fact_os_package_repositories }}"
    configuration_directories: "{{ configuration_directories + fact_configuration_directories }}"
    cron_jobs: "{{ cron_jobs + fact_cron_jobs }}"
    files_to_configure: "{{ files_to_configure + fact_files_to_configure }}"
    files_to_download: "{{ files_to_download + fact_files_to_download }}"
    os_groups: "{{ os_groups + fact_os_groups }}"
    os_services: "{{ os_services + fact_os_services }}"
    templates_to_render: "{{ templates_to_render + fact_templates_to_render }}"

- name: Register additional setup facts if stack is enabled for {{ fact_category }}
  ansible.builtin.set_fact:
    docker_compose_up_items: "{{ docker_compose_up_items + fact_docker_compose_up_items }}"
    os_users: "{{ os_users + fact_os_users }}"
  when:
    - fact_enable_custom_fact

# We added a 'state' attribute set to 'absent' if the stack is disabled so those files will
# eventually get deleted
- name: Register cleanup facts if stack is disabled for {{ fact_category }}
  ansible.builtin.set_fact:
    files_to_configure: "{{ files_to_configure + fact_files_to_download + fact_templates_to_render }}"
  when:
    - not fact_enable_custom_fact
...
