---
- name: Register facts for {{ fact_category }}
  ansible.builtin.set_fact:
    apt_packages_to_install: "{{ apt_packages_to_install + fact_os_packages_to_install }}"
    apt_packages_to_uninstall: "{{ apt_packages_to_uninstall + fact_os_packages_to_uninstall }}"
    apt_repositories_to_add: "{{ apt_repositories_to_add + fact_os_package_repositories_to_add }}"
    configuration_directories_to_copy: "{{ configuration_directories_to_copy + fact_configuration_directories_to_copy }}"
    configuration_directories_to_create: "{{ configuration_directories_to_create + fact_configuration_directories_to_create }}"
    deb_packages_to_install: "{{ deb_packages_to_install + fact_deb_packages_to_install }}"
    docker_compose_up_items: "{{ docker_compose_up_items + fact_docker_compose_up_items }}"
    files_to_download: "{{ files_to_download + fact_files_to_download }}"
    os_groups_to_create: "{{ os_groups_to_create + fact_os_groups_to_create }}"
    os_services_to_configure: "{{ os_services_to_configure + fact_os_services_to_configure }}"
    os_users_to_create: "{{ os_users_to_create + fact_os_users_to_create }}"
    templates_to_render: "{{ templates_to_render + fact_templates_to_render }}"
...
