---
# These setup facts are needed regardless of the flag to enable or disable a given stack
- name: Register setup facts for {{ fact_category }}
  ansible.builtin.set_fact:
    apt_packages: "{{ apt_packages + fact_os_packages }}"
    cron_jobs: "{{ cron_jobs + fact_cron_jobs }}"
    files_to_remove: "{{ files_to_remove + fact_files_to_remove }}"

# These setup facts are needed only when a given stack is enabled
- name: Register in-depth setup facts for {{ fact_category }}
  ansible.builtin.set_fact:
    apt_repositories_to_add: "{{ apt_repositories_to_add + fact_os_package_repositories_to_add }}"
    configuration_directories_to_copy: "{{ configuration_directories_to_copy + fact_configuration_directories_to_copy }}"
    configuration_directories_to_create: "{{ configuration_directories_to_create + fact_configuration_directories_to_create }}"
    docker_compose_up_items: "{{ docker_compose_up_items + fact_docker_compose_up_items }}"
    files_to_download: "{{ files_to_download + fact_files_to_download }}"
    os_groups_to_create: "{{ os_groups_to_create + fact_os_groups_to_create }}"
    os_services_to_configure: "{{ os_services_to_configure + fact_os_services_to_configure }}"
    os_users_to_create: "{{ os_users_to_create + fact_os_users_to_create }}"
    templates_to_render: "{{ templates_to_render + fact_templates_to_render }}"
  when:
    - fact_enable_custom_fact

# Check if we need to skip the configuration of DNS records.
# Skipping this configuration may be userful if services are not going to start, and we don't want to update the DNS zone yet.
# This task eventually skips the DNS records that are explicitly added to fact_dns_records_to_configure
# because we assume they are for service reachability, but if we're not starting any service there's
# no point in adding those records to the DNS zone.
# This task doesn't skip the DNS records that are dynamically generated, from other
# sources.
- name: Register DNS records facts for {{ fact_category }}
  ansible.builtin.set_fact:
    dns_records_to_configure: "{{ dns_records_to_configure + fact_dns_records_to_configure }}"
  when:
    - fact_configure_dns_records
    - fact_enable_custom_fact
...
