---
- name: Populate the edge environment DNS resolvers list
  ansible.builtin.set_fact:
    network_stack_edge_dns_resolvers: "{{ network_stack_edge_dns_resolvers + [item] }}"
  with_items:
    # The dnsmasq instance on the gateway acts both as a resolver and as a DNS
    # server for the edge environment
    - "{{ edge_dns_server }}"

- name: Add the edge environment recursive DNS resolvers to the DNS resolvers list
  ansible.builtin.set_fact:
    network_stack_edge_dns_resolvers: "{{ network_stack_edge_dns_resolvers + network_stack_edge_dns_resolver_template }}"
  when:
    - hostvars[item].network_stack_configure_recursive_dns_resolver is defined
    - hostvars[item].network_stack_configure_recursive_dns_resolver
  with_items: "{{ groups['all'] }}"

- name: Debug network_stack_edge_dns_resolvers
  ansible.builtin.debug:
    var: network_stack_edge_dns_resolvers
    verbosity: 1
...
