---
# These setup facts are needed regardless of the flag to enable or disable a given stack
- name: Register setup facts for {{ fact_category }}
  ansible.builtin.set_fact:
    apt_packages: "{{ apt_packages + fact_os_packages }}"
    apt_repositories: "{{ apt_repositories + fact_os_package_repositories }}"
    cron_jobs: "{{ cron_jobs + fact_cron_jobs }}"
    files_to_remove: "{{ files_to_remove + fact_files_to_remove }}"
    os_groups: "{{ os_groups + fact_os_groups }}"
    os_users: "{{ os_users + fact_os_users }}"
    os_services: "{{ os_services + fact_os_services }}"

- name: Register additional setup facts if {{ fact_category }} is enabled
  ansible.builtin.set_fact:
    configuration_directories_to_copy: "{{ configuration_directories_to_copy + fact_configuration_directories_to_copy }}"
    configuration_directories_to_create: "{{ configuration_directories_to_create + fact_configuration_directories_to_create }}"
    docker_compose_up_items: "{{ docker_compose_up_items + fact_docker_compose_up_items }}"
    files_to_download: "{{ files_to_download + fact_files_to_download }}"
    templates_to_render: "{{ templates_to_render + fact_templates_to_render }}"
  when:
    - fact_enable_custom_fact

# TODO: exclude system-wide configuration directories
# TODO: delete contents in fact_configuration_directories_to_copy (the destination might be a system directory)

- name: Register cleanup facts if {{ fact_category }} is disabled
  ansible.builtin.set_fact:
    files_to_remove: "{{ files_to_remove + fact_configuration_directories_to_create + fact_files_to_download + fact_templates_to_render }}"
  when:
    - not fact_enable_custom_fact

# Check if we need to skip the configuration of DNS records.
# Skipping this configuration may be userful if services are not going to start, and we don't want to update the DNS zone yet.
# This task eventually skips the DNS records that are explicitly added to fact_dns_records_to_configure
# because we assume they are for service reachability, but if we're not starting any service there's
# no point in adding those records to the DNS zone.
# This task doesn't skip the DNS records that are dynamically generated, from other
# sources.
- name: Register DNS records facts for {{ fact_category }}
  ansible.builtin.set_fact:
    dns_records_to_configure: "{{ dns_records_to_configure + fact_dns_records_to_configure }}"
  when:
    - fact_configure_dns_records
    - fact_enable_custom_fact
...
