---
- name: Add monitoring backend configuration directories to the list of configuration directories to create
  ansible.builtin.set_fact:
    configuration_directories_to_create: "{{ configuration_directories_to_create + monitoring_backend_configuration_directories }}"

- name: Add monitoring backend configuration directories to the list of configuration directories to copy
  ansible.builtin.set_fact:
    configuration_directories_to_copy: "{{ configuration_directories_to_copy + monitoring_backend_configuration_directories_to_copy }}"

- name: Add monitoring backend docker compoose up items to the list of docker compose up items
  ansible.builtin.set_fact:
    docker_compose_up_items: "{{ docker_compose_up_items + monitoring_backend_docker_compose_up_items }}"

- name: Add monitoring backend templates to render items to the list of templates to render
  ansible.builtin.set_fact:
    templates_to_render: "{{ templates_to_render + monitoring_backend_templates_to_render }}"
...
