---
- name: Run docker-compose up in detached mode
  debugger: on_failed
  changed_when: '"Started" in docker_compose_up_result.stdout or "Started" in docker_compose_up_result.stderr'
  ansible.builtin.command: >
    docker compose \
    --file {{ item.compose_file_path }} \
    up \
    --build \
    --detach \
    --remove-orphans
  register: docker_compose_up_result
  with_items: "{{ docker_compose_up_items }}"

- name: Debug Docker Compose output
  ansible.builtin.debug:
    var: docker_compose_up_result
    verbosity: 1
...
