---
- name: "Delete {{ systemd_journal_file_path }}"
  ansible.builtin.file:
    path: "{{ systemd_journal_file_path }}"
    state: absent
  notify: restart journald
  when: delete_systemd_journal_file

- name: Copy journald configuration files in place
  ansible.builtin.template:
    src: "systemd/journald/{{ item }}.jinja"
    dest: "{{ systemd_journald_configuration_directory_path }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart journald
  with_items:
    - 001-journald.conf
...
