---
- name: Add Sense Hat config file values to the config file values dictionary
  set_fact:
    raspberry_pi_config_file_values: "{{ raspberry_pi_config_file_values | combine({item.key: item.value}) }}"
  with_dict: "{{ raspberry_pi_sense_hat_config_txt_values }}"
  when: has_sense_hat

- name: "Configure {{ raspberry_pi_config_file_path }}"
  lineinfile:
    line: "{{ item.key }}={{ item.value }}"
    dest: "{{ raspberry_pi_config_file_path }}"
    regexp: "^{{ item.key }}="
  notify: Reboot host and wait for it to restart
  with_dict: "{{ raspberry_pi_config_file_values }}"

# Those packages will be installed in the setup-Debian.yaml
- name: Add Sense Hat APT packages list to the APT packages to install list
  set_fact:
    apt_packages_to_install: "{{ apt_packages_to_install + raspberry_pi_sense_hat_apt_packages }}"
  when: has_sense_hat
...
