---
- name: Get Tailscale status
  command: tailscale status --json
  register: tailscale_status

- name: Debug tailscale_status
  ansible.builtin.debug:
    var: tailscale_status
    verbosity: 1

- name: Enable IP packet forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    reload: true
    state: present
    sysctl_set: true
    value: "1"
  become: true
  when:
    - tailscale_up_advertise_edge_environment_routes
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: Configure the tailscale up command to advertise edge environment routes
  ansible.builtin.set_fact:
    tailscale_up_command: "{{ tailscale_up_command }} --advertise-routes={{ edge_environment_subnet }}"
  when:
    - tailscale_up_advertise_edge_environment_routes

- name: Debug tailscale_up_command
  ansible.builtin.debug:
    var: tailscale_up_command
    verbosity: 1

- name: Run Tailscale up
  become: true
  command: "{{ tailscale_up_command }}"
  register: tailscale_up_output

- name: Debug tailscale_up_output
  ansible.builtin.debug:
    var: tailscale_up_output
    verbosity: 1
...
