---
- name: Add Sense Hat config file values to the config file values dictionary
  set_fact:
    raspberry_pi_config_file_values: "{{ raspberry_pi_config_file_values | combine({item.key: item.value}) }}"
  with_dict: "{{ raspberry_pi_sense_hat_config_txt_values }}"
  when: has_sense_hat

- name: "Configure {{ raspberry_pi_config_file_path }}"
  lineinfile:
    line: "{{ item.key }}={{ item.value }}"
    dest: "{{ raspberry_pi_config_file_path }}"
    regexp: "^{{ item.key }}="
  notify: Reboot host and wait for it to restart
  with_dict: "{{ raspberry_pi_config_file_values }}"

- name: Install APT packages for the Raspberry Pi Sense Hat
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ raspberry_pi_sense_hat_apt_packages }}"
  when: has_sense_hat
...
