---
- name: Set authorized key for the {{ ansible_user }} user, from {{ home_lab_node_ssh_public_key_path }}
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', home_lab_node_ssh_public_key_path) }}"
  when: home_lab_node_ssh_public_key_path is defined
...
