---
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', 'files/ssh/home-lab-node-key.pub') }}"

- name: "Disable password login for the default user: {{ ansible_user }}"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password_lock: true
...
