---
- name: Create OS groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: present
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ os_groups_to_create }}"

- name: Create OS users
  ansible.builtin.user:
    append: "{{ item.append | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    create_home: "{{ item.create_home | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    password_lock: "{{ item.password_lock | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    state: present
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ os_users_to_create }}"

- name: "Lock the password of the default user if we authenticated with a key - {{ ansible_user }}"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password_lock: true
  # Make sure that we authenticated with a key before locking the password
  when: ansible_password is not defined

- name: Set authorized key for the user - {{ ansible_user }}
  ansible.posix.authorized_key:
    exclusive: true
    key: "{{ lookup('file', home_lab_node_ssh_public_key_path) }}"
    state: present
    user: "{{ ansible_user }}"
  when: home_lab_node_ssh_public_key_path | length > 0

- name: Add configured user accounts to passwordless sudoers
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: "0644"
  with_items: "{{ security_sudoers_passwordless }}"

- name: Add configured user accounts to passworded sudoers
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: "0644"
  with_items: "{{ security_sudoers_passworded }}"
...
