---
- name: "Create the default user: {{ ansible_user }}"
  ansible.builtin.user:
    append: true
    name: "{{ ansible_user }}"
    groups: "{{ default_user_groups }}"
    # Don't lock the password here because we want to be sure to set up key-based authentication first

- name: "Lock the password of the default user: {{ ansible_user }}"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password_lock: true
  # Make sure that we authenticated with a key before locking the password
  when: ansible_password is not defined
...
