---
# Customize the following values as needed
esphome_api_encryption_key: "g2jF6JiWbKtL1tQd32XoGwDYqq503MjDe4xqJbQc4to="
esphome_ota_password: "esphome_ota_password"
wifi_fallback_hostspot_password: "fallback_hotspot_password"
wifi_password: "wifi_password"
wifi_ssid: "wifi_ssid"
