---
# Customize the following values as needed
esphome_api_encryption_key: "ZXNwaG9tZV9hcGlfZW5jcnlwdGlvbl9rZXkK"
esphome_ota_password: "esphome_ota_password"
wifi_fallback_hostspot_password: "fallback_hotspot_password"
wifi_password: "wifi_password"
wifi_ssid: "wifi_ssid"
...
