---
# Customize the following values as needed
home_assistant_api_key: "home_assistant_api_key"
wifi_fallback_hostspot_password: "fallback_hotspot_password"
wifi_password: "wifi_password"
wifi_ssid: "wifi_ssid"
...
