---
# Customize the following values as needed
esphome_ota_password: "esphome_ota_password"
wifi_fallback_hostspot_password: "fallback_hotspot_password"
wifi_password: "wifi_password"
wifi_ssid: "wifi_ssid"
...
