---
# Enable Home Assistant API
api:
  password: !secret home_assistant_api_key

captive_portal: null

display:
  - platform: lcd_pcf8574
    dimensions: ${lcd_width}x${lcd_height}
    address: 0x27
    lambda: |-
      it.printf(0, 0, "IP: %s", id(wifi_ip_v4_address).state.c_str());
      it.printf(0, 2, "Distance: %.2f cm", id(ultrasonic_distance_sensor).state);

      static int p1 = 0;

      char const *fqdn = "FQDN: ${fqdn}";
      int fqdn_length = strlen(fqdn);
      if (fqdn_length > ${lcd_width}) fqdn_length = ${lcd_width};

      int spaces_length = fqdn_length >= ${lcd_width} ? 0 : ${lcd_width} - fqdn_length + 1;
      char spaces[spaces_length];
      for (int i = 0; i < spaces_length - 1; i++) spaces[i] = ' ';
      spaces[spaces_length - 1] = '\0';

      it.printf(0, 1, "%.*s%s", fqdn_length, fqdn + p1, spaces);

      p1++;
      if(p1 > strlen(fqdn) - ${lcd_width}) {
        p1 = 0;
      }

      it.printf(0, 3, "                    ");
      if (id(extend_actuators).state) {
        it.printf(0, 3, "Extending actuators");
      } else if (id(retract_actuators).state) {
        it.printf(0, 3, "Retracting actuators");
      } else {
        it.printf(0, 3, "Actuators stopped");
      }
    update_interval: 1s

esp32:
  board: featheresp32
  framework:
    type: arduino

esphome:
  name: smart-desk

i2c:
  sda: 23
  scl: 22

light:
  - platform: status_led
    name: "ESP32 Status LED"
    pin: GPIO13

# Enable logging
logger: null

number:
  - id: target_smart_desk_distance
    platform: template
    icon: "mdi:desk"
    name: "Desired desk top distance from sensor"
    min_value: ${min_desk_distance}
    max_value: ${max_desk_distance}
    optimistic: true
    step: 0.01
    unit_of_measurement: m
    on_value:
      - script.execute: operate_actuators

ota:
  password: !secret home_assistant_api_key

prometheus: null

script:
  - id: operate_actuators
    then:
      - if:
          condition:
            lambda: |-
              return id(ultrasonic_distance_sensor).state < id(target_smart_desk_distance).state;
          then:
            - logger.log: "Current distance < requested distance. Extending the actuators."
            - script.execute: extend_actuators_script
          else:
            - logger.log: "Current distance > requested distance. Retracting the actuators."
            - script.execute: retract_actuators_script
  - id: extend_actuators_script
    then:
      - logger.log: "Extending the actuators..."
      # No need to turn off the other relays because the interlock group takes care of that
      - switch.turn_on: desk_relay_1
      - switch.turn_on: desk_relay_3
      # Turn the actuators off anyway as a safety measure
      - delay: 1min
      - logger.log: "Safety timer expired. Stopping the actuators. Stopping the actuators in any case."
      - script.execute: turn_actuators_off_script
  - id: retract_actuators_script
    then:
      - logger.log: "Retracting the actuators..."
      # No need to turn off the other relays because the interlock group takes care of that
      - switch.turn_on: desk_relay_2
      - switch.turn_on: desk_relay_4
      # Turn the actuators off anyway as a safety measure
      - delay: 1min
      - logger.log: "Safety timer expired. Stopping the actuators in any case."
      - script.execute: turn_actuators_off_script
  - id: turn_actuators_off_script
    then:
      - logger.log: "Turning the actuators off..."
      - switch.turn_off: desk_relay_1
      - switch.turn_off: desk_relay_2
      - switch.turn_off: desk_relay_3
      - switch.turn_off: desk_relay_4
      # Stop the other scripts because they might be running and waiting for the
      # safety timer to expire, but we explicitly stop the actuators here, so
      # there's no need for the safety timer at this point.
      - script.stop: extend_actuators_script
      - script.stop: retract_actuators_script

sensor:
  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();
  - id: ultrasonic_distance_sensor
    platform: ultrasonic
    trigger_pin: GPIO27
    echo_pin: GPIO15
    name: "Ultrasonic distance sensor"
    update_interval: 100ms
    timeout: 4m
    on_value:
      - if:
          condition:
            lambda: |-
              return id(extend_actuators).state || id(retract_actuators).state;
          then:
            - logger.log: "The actuators are moving. Checking if the desk reached the target distance..."
            - if:
                condition:
                  lambda: |-
                    float diff = id(ultrasonic_distance_sensor).state - id(target_smart_desk_distance).state;
                    float abs_diff = abs(diff);
                    float distance_tolerance = ${distance_tolerance};
                    ESP_LOGD("main", "Difference: %f, Abs difference: %f, Tolerance: %f", diff, abs_diff, distance_tolerance);
                    if (abs_diff < distance_tolerance){
                      ESP_LOGD("main", "Abs difference is in the tolerance range. Condition matched.");
                      return true;
                    } else {
                      ESP_LOGD("main", "Abs difference is not in the tolerance range. Condition not matched.");
                      return false;
                    }
                then:
                  - logger.log: "The desk reached the target distance. Stopping the actuators..."
                  - script.execute: turn_actuators_off_script
                else:
                  - logger.log: "The desk didn't reach the target distance yet. Leaving the actuators on..."
          else:
            - logger.log: "The actuators are not moving. Skipping the desk distance check."
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 30s

switch:
  - id: desk_relay_1
    interlock: &interlock_group_actuator_1 [desk_relay_1, desk_relay_2]
    platform: gpio
    pin:
      inverted: true
      number: 33
    restore_mode: ALWAYS_OFF
    name: "Desk relay 1"
  - id: desk_relay_2
    interlock: *interlock_group_actuator_1
    platform: gpio
    pin:
      inverted: true
      number: 32
    restore_mode: ALWAYS_OFF
    name: "Desk relay 2"
  - id: desk_relay_3
    interlock: &interlock_group_actuator_2 [desk_relay_3, desk_relay_4]
    platform: gpio
    pin:
      inverted: true
      number: 14
    restore_mode: ALWAYS_OFF
    name: "Desk relay 3"
  - id: desk_relay_4
    interlock: *interlock_group_actuator_2
    platform: gpio
    pin:
      inverted: true
      number: 12
    restore_mode: ALWAYS_OFF
    name: "Desk relay 4"
  - id: extend_actuators
    platform: template
    name: "Extend actuators"
    lambda: |-
      if (id(desk_relay_1).state && id(desk_relay_3).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - script.execute: extend_actuators_script
    turn_off_action:
      - script.execute: turn_actuators_off_script
  - id: retract_actuators
    platform: template
    name: "Retract actuators"
    lambda: |-
      if (id(desk_relay_2).state && id(desk_relay_4).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - script.execute: retract_actuators_script
    turn_off_action:
      - script.execute: turn_actuators_off_script

substitutions:
  device_name_upper: Smart Desk
  device_name: smart-desk
  fqdn: ${device_name}.${network_domain}
  lcd_height: "4"
  lcd_width: "20"
  distance_tolerance: "0.02"
  # 19.5 cm is the distance between the mount point and the desk top if the controller box is placed on the horizontal table reinforcement
  min_desk_distance: "0.19"
  max_actuators_extension: "0.35"
  # 54 cm is the distance between the mount point and the desk top if the controller box is placed on the ground
  # this is min_desk_distance + max_actuators_extension
  max_desk_distance: "0.54"
  network_domain: edge.lab.ferrari.how

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
  - platform: wifi_info
    ip_address:
      id: wifi_ip_v4_address
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results

web_server: null

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name_upper} Fallback Hotspot"
    password: !secret wifi_fallback_hostspot_password
  domain: .${network_domain}
  password: !secret wifi_password
  ssid: !secret wifi_ssid
...
