---
configure_docker: true
configure_frigate: true
configure_mqtt_broker: true
configure_network_shares: true
configure_network_stack: true
configure_torrent: true
configure_zigbee2mqtt: true
disks_to_mount:
  - fstype: ext4
    opts: noatime
    path: /media/data0
    src: UUID=3fb762aa-c397-460b-809c-9ac741ce14f1
    state: mounted
has_argonone_case: true
network_stack_configure_recursive_dns_resolver: true
samba_shares:
  - comment: "Backups-Marco"
    create_mask: "0744"
    directory_group: "marco"
    directory_mask: "0755"
    directory_owner: "marco"
    force_group: "marco"
    force_user: "marco"
    name: "backups-marco"
    path: "/media/data0/backups-marco"
    read_only: "yes"
    valid_users: "marco"
    write_list: "marco"
  - comment: "Media"
    create_mask: "0744"
    directory_group: users
    directory_mask: "0755"
    directory_owner: "{{ ansible_user }}"
    force_group: "users"
    force_user: "{{ ansible_user }}"
    name: "media"
    path: "/media/data0/media"
    read_only: "yes"
    valid_users: "@{{ samba_default_readers_group_name }}"
    write_list: "@{{ samba_default_writers_group_name }}"
samba_os_users_to_create:
  - append: true
    name: "{{ ansible_user }}"
    groups:
      - "{{ samba_default_readers_group_name }}"
      - "{{ samba_default_writers_group_name }}"
  - append: true
    name: "marco"
    groups:
      - "{{ samba_default_readers_group_name }}"
      - "{{ samba_default_writers_group_name }}"
torrent_download_path: "/media/data0/media/downloads"
zigbee_adapter_device_path: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220708144056-if00"
...
