---
- name: Restart the connman service
  service:
    name: connman
    state: restarted
  listen: "restart_connman"

- name: Restart SSH Daemon
  service:
    name: sshd
    state: restarted
  listen: "restart_sshd"
