---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', 'gcr.io/$PROJECT_ID/arm-image-builder:$_ARM_BUILDER_IMAGE_TAG']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', '$_DOCKER_BUILDX_BUILDER_NAME']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'use', '$_DOCKER_BUILDX_BUILDER_NAME']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '-t', 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_ID:$_DOCKER_IMAGE_TAG', '--build-arg', 'CONFIGURATION_DIRECTORY_PATH=$_RENDERED_TEMPLATES_PATH', '--push', '.']
options:
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'
substitutions:
  _ARM_BUILDER_IMAGE_TAG: '4a17db0'
  _CLOUD_SDK_IMAGE_TAG: 'alpine'
  _DOCKER_BUILDX_BUILDER_NAME: 'multiarch_builder'
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64'
