---
- name: Send Wake-on-LAN magic packets
  community.general.wakeonlan:
    mac: "{{ item.mac_address }}"
  # Don't report changes because this task always report a status
  # of 'changed', breaking idempotence tests
  changed_when: false
  delegate_to: localhost
  with_items: "{{ network_interfaces }}"
  when:
    - network_interfaces is defined
    - item.mac_address is defined

- name: Wait for the machines to come online
  ansible.builtin.wait_for_connection:
    timeout: 600
