---
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-os-images/esp32'
    paths: ["./build/smart-desk-*.bin"]
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - -c
      - |
        PROJECT_EXECUTABLE_TAG=$COMMIT_SHA
        export PROJECT_EXECUTABLE_TAG
        make
    entrypoint: '/bin/bash'
...
