{
 "title": "Nix: comin",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(comin_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reboot needed - $host",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "repeat": "host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "comin_need_to_reboot{instance=~\"^$host$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eval status - $host",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "repeat": "host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "comin_last_deployment_failed{instance=~\"^$host$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Poller suspended - $host",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
   "repeat": "host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "comin_is_suspended{instance=~\"^$host$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment status - $host",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 25 },
   "repeat": "host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "comin_last_deployment_failed{instance=~\"^$host$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  },
  {
   "title": "Live deployment status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "comin_deployment_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pipeline health and activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true
  },
  {
   "title": "Fetch rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(comin_fetch_count{instance=~\"^$host$\"}[5m]) * 60",
     "legendFormat": "{{instance}} ({{remote_name}} - {{status}})"
    }
   ]
  },
  {
   "title": "Pipeline Failure Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "comin_last_fetch_failed{instance=~\"^$host$\"}",
     "legendFormat": "{{instance}} - {{__name__}}"
    },
    {
     "expr": "comin_last_eval_failed{instance=~\"^$host$\"}",
     "legendFormat": "{{instance}} - {{__name__}}"
    },
    {
     "expr": "comin_last_build_failed{instance=~\"^$host$\"}",
     "legendFormat": "{{instance}} - {{__name__}}"
    }
   ]
  }
 ]
}