{
 "title": "Home network",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ONT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Device information",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "group by (model, hardware_version, bootloader_version, software_version, pon_serial_number) (ztef6005ont_device_info)"
    }
   ]
  },
  {
   "title": "GPON status",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "group by (pon_serial_number, flag) (ztef6005ont_gpon_status==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethernet network interface link type",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "group by (pon_serial_number, mac_address, flag) (ztef6005ont_ethernet_interface_link_type==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethernet interface link status",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "group by (pon_serial_number, mac_address, flag) (ztef6005ont_ethernet_interface_link_up==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Optical network interface power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "ztef6005ont_optical_tx_power_dbm",
     "legendFormat": "{{__name__}} - {{pon_serial_number}}"
    },
    {
     "expr": "ztef6005ont_optical_rx_power_dbm",
     "legendFormat": "{{__name__}} - {{pon_serial_number}}"
    }
   ]
  },
  {
   "title": "Optical network interface temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ztef6005ont_optical_interface_temperature_celsius",
     "legendFormat": "{{__name__}} - {{pon_serial_number}}"
    }
   ]
  },
  {
   "title": "Optical network interface current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "ztef6005ont_optical_interface_current_amperes / 1000",
     "legendFormat": "{{__name__}} - {{pon_serial_number}}"
    }
   ]
  },
  {
   "title": "Optical network interface voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ztef6005ont_optical_interface_voltage_volts",
     "legendFormat": "{{__name__}} - {{pon_serial_number}}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ztef6005ont_ethernet_interface_tx_bytes",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    },
    {
     "expr": "ztef6005ont_ethernet_interface_rx_bytes",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    }
   ]
  },
  {
   "title": "Network traffic (packets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ztef6005ont_ethernet_interface_tx_packets",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    },
    {
     "expr": "ztef6005ont_ethernet_interface_rx_packets",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    }
   ]
  },
  {
   "title": "Network traffic (unicast packets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ztef6005ont_ethernet_interface_tx_unicast_packets",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    },
    {
     "expr": "ztef6005ont_ethernet_interface_rx_unicast_packets",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    }
   ]
  },
  {
   "title": "Network traffic (multicast packets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ztef6005ont_ethernet_interface_tx_multicast_packets",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    },
    {
     "expr": "ztef6005ont_ethernet_interface_rx_multicast_packets",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    }
   ]
  },
  {
   "title": "Network traffic (errors)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ztef6005ont_ethernet_interface_tx_errors",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    },
    {
     "expr": "ztef6005ont_ethernet_interface_rx_errors",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    }
   ]
  },
  {
   "title": "Network traffic (drops)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ztef6005ont_ethernet_interface_tx_drops",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    },
    {
     "expr": "ztef6005ont_ethernet_interface_rx_drops",
     "legendFormat": "{{__name__}} - {{mac_address}} - {{pon_serial_number}}"
    }
   ]
  },
  { "title": "ICMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "ICMP Probe",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ping\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Count of ICMP probe failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(probe_success{job=\"blackbox-ping\"} == 0)"
    }
   ]
  },
  {
   "title": "Total ICMP Probe duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (probe_icmp_duration_seconds)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Probe duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_icmp_duration_seconds", "legendFormat": "{{instance}} - {{phase}}" }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Probe",
     "type": "state-timeline",
     "gridPos": { "h": 30, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "probe_success{job=~\"blackbox-dns.*\"}",
       "legendFormat": "{{job}} - DNS Server: {{instance}}"
      }
     ]
    },
    {
     "title": "Total DNS Probe duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (job) (probe_dns_duration_seconds)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS Probe duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "probe_dns_duration_seconds", "legendFormat": "{{job}} - {{phase}}" }
     ]
    },
    {
     "title": "Average DNS Probe duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (job) (avg_over_time(probe_dns_duration_seconds[$__range]))"
      }
     ]
    },
    {
     "title": "Average DNS probe by resolver",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "avg by (instance) (probe_dns_duration_seconds != 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Endpoints",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-http-2xx\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}