---
- name: Setup Proxmox OS packages and repositories
  ansible.builtin.include_tasks:
    file: setup-proxmox-os-packages.yaml

- name: Setup kernel
  ansible.builtin.include_tasks:
    file: setup-kernel.yaml

- name: Create Proxmox directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
  become: true
  with_items:
    - path: "{{ proxmox_raws_directory_path }}"
    - path: "{{ proxmox_snippets_directory_path }}"

- name: Render cloud-init network snippets
  ansible.builtin.template:
    src: templates/cloud-init/network.yaml.jinja
    dest: "{{ proxmox_snippets_directory_path }}/cloud-init-{{ item.hostname }}-network.yaml"
    owner: root
    group: root
    mode: "0644"
  become: true
  vars:
    cloud_init_instance_mac_address: "{{ item.default_network_interface_mac_address }}"
  with_items: "{{ proxmox_vms | default([]) }}"

- name: Render cloud-init user-data snippets
  ansible.builtin.template:
    src: templates/cloud-init/user-data.yaml.jinja
    dest: "{{ proxmox_snippets_directory_path }}/cloud-init-{{ item.hostname }}-user-data.yaml"
    owner: root
    group: root
    mode: "0644"
  become: true
  vars:
    cloud_init_instance_hostname: "{{ item.hostname }}"
  with_items: "{{ proxmox_vms | default([]) }}"

- name: Download images and disks
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}/"
    mode: "0644"
    checksum: "{{ item.checksum }}"
  become: true
  with_items:
    - url: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.8.0-amd64-netinst.iso
      checksum: "sha512:https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA512SUMS"
      dest: "{{ proxmox_isos_directory_path }}"
    - url: https://cloud.debian.org/images/cloud/bookworm/20241110-1927/debian-12-generic-amd64-20241110-1927.raw
      checksum: "sha512:https://cloud.debian.org/images/cloud/bookworm/20241110-1927/SHA512SUMS"
      dest: "{{ proxmox_raws_directory_path }}"

- name: Delete old images and disks
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  become: true
  with_items:
    - path: "{{ proxmox_isos_directory_path }}/debian-12.5.0-amd64-netinst.iso"
    - path: "{{ proxmox_raws_directory_path }}/debian-12-generic-amd64-20240211-1654.raw"
