---
options:
    env:
        - TF_INPUT=false
steps:
    - id: 'decrypt secrets'
      name: gcr.io/cloud-builders/gcloud
      entrypoint: 'sh'
      dir: "$_TERRAFORM_ENVIRONMENT_PATH"
      args:
          - '-c'
          - |
            /builder/google-cloud-sdk/bin/gcloud \
                kms decrypt \
                --ciphertext-file=terraform.tfvars.enc \
                --plaintext-file=terraform.tfvars \
                --location=global \
                --keyring=cloud-build-keyring \
                --key=cloudbuild-crypto-key
    - id: 'tf init'
      name: 'hashicorp/terraform:$_TERRAFORM_IMAGE_TAG'
      entrypoint: 'sh'
      dir: "$_TERRAFORM_ENVIRONMENT_PATH"
      args:
          - '-c'
          - |
            terraform init || exit 1
            cd ../../
    - id: 'tf validate'
      name: 'hashicorp/terraform:$_TERRAFORM_IMAGE_TAG'
      entrypoint: 'sh'
      dir: "$_TERRAFORM_ENVIRONMENT_PATH"
      args:
          - '-c'
          - |
            terraform validate || exit 1
            cd ../../
    - id: 'tf plan'
      name: 'hashicorp/terraform:$_TERRAFORM_IMAGE_TAG'
      entrypoint: 'sh'
      dir: "$_TERRAFORM_ENVIRONMENT_PATH"
      args:
          - '-c'
          - |
            terraform plan
    - id: 'tf apply'
      name: 'hashicorp/terraform:$_TERRAFORM_IMAGE_TAG'
      entrypoint: 'sh'
      dir: "$_TERRAFORM_ENVIRONMENT_PATH"
      args:
          - '-c'
          - |
            if [ "${BRANCH_NAME}" = "master" ]; then
                echo $BRANCH_NAME
                terraform apply -auto-approve || exit 1
            else
                echo "Not applying any Terraform change. Not on master branch."
                echo "Current branch: $BRANCH_NAME"
            fi
substitutions:
    _TERRAFORM_ENVIRONMENT_PATH: 'provisioning/terraform/environments/prod'
    _TERRAFORM_IMAGE_TAG: '0.12.29'
tags: ['$PROJECT_ID', '$BUILD_ID', '$_PR_NUMBER', '$REPO_NAME', '$COMMIT_SHA', '$SHORT_SHA', '$BRANCH_NAME', '$TAG_NAME']
