---
options:
  env:
    - TF_IN_AUTOMATION=true
    - TF_INPUT=false
steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:$_TERRAFORM_IMAGE_TAG'
    entrypoint: 'sh'
    dir: "$_TERRAFORM_ENVIRONMENT_PATH"
    args:
      - '-c'
      - |
        echo "Contents of $(pwd): $(ls -al)"
        terraform init
  - id: 'tf validate'
    name: 'hashicorp/terraform:$_TERRAFORM_IMAGE_TAG'
    entrypoint: 'sh'
    dir: "$_TERRAFORM_ENVIRONMENT_PATH"
    args:
      - '-c'
      - |
        terraform validate
  - id: 'tf plan'
    name: 'hashicorp/terraform:$_TERRAFORM_IMAGE_TAG'
    entrypoint: 'sh'
    dir: "$_TERRAFORM_ENVIRONMENT_PATH"
    args:
      - '-c'
      - |
        terraform plan -out=tfplan
  - id: 'tf apply'
    name: 'hashicorp/terraform:$_TERRAFORM_IMAGE_TAG'
    entrypoint: 'sh'
    dir: "$_TERRAFORM_ENVIRONMENT_PATH"
    args:
      - '-c'
      - |
        echo "Current branch: $BRANCH_NAME"
        if [ "${BRANCH_NAME}" = "master" ]; then
            terraform apply -auto-approve tfplan
        else
            echo "Not applying any Terraform change. Not on master branch."
        fi
substitutions:
  _CLOUD_SDK_IMAGE_TAG: 'alpine'
  _TERRAFORM_IMAGE_TAG: '0.15.3'
timeout: 37000s
