---
apt_cache_valid_time: 3600
docker_repositories_to_add:
  - repository_key_keyring_file_path: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
    repository_key_url: "{{ docker_repository_url }}/{{ ansible_distribution | lower }}/gpg"
    repository_url: "deb [arch={{ dpkg_architecture }}] {{ docker_repository_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    state: "{{ configure_docker | ternary('present', 'absent') }}"
docker_os_packages:
  - name: apt-transport-https
  - name: ca-certificates
  - name: docker-ce
    state: "{{ configure_docker | ternary('present', 'absent') }}"
  - name: docker-compose-plugin
    state: "{{ configure_docker | ternary('present', 'absent') }}"
  - name: gnupg
  - name: containerd
    purge: true
    state: "absent"
  - name: docker
    purge: true
    state: "absent"
  - name: docker-engine
    purge: true
    state: "absent"
  - name: docker.io
    purge: true
    state: "absent"
  - name: runc
    purge: true
    state: "absent"
docker_service_name: docker
...
