---
all:
  children:
    edge:
      children:
        home_lab: null
    home_lab:
      children:
        home_lab_raspberry_pis: null
        home_lab_proxmox_nodes: null
    home_lab_raspberry_pis:
      hosts:
        raspberrypi.edge.lab.ferrari.how: null
        raspberrypi2.edge.lab.ferrari.how: null
        raspberrypi3.edge.lab.ferrari.how: null
    home_lab_proxmox_nodes:
      hosts:
        pve1.edge.lab.ferrari.how:
          network_interfaces:
            - mac_address: "7c:83:34:be:3f:23"
              interface_name: enp1s0
            - mac_address: "7c:83:34:be:3f:24"
              interface_name: enp2s0
...
