variable "compute_engine_development_workstation_ssh_public_key_file_path" {}
variable "configuration_bucket_name" {}
variable "development_workstation_boot_disk_size" {}
variable "development_workstation_git_repositories_to_clone" {}
variable "development_workstation_machine_type" {}
variable "development_workstation_min_cpu_platform" {}
variable "development_workstation_name" {}
variable "development_workstation_region" {}
variable "development_workstation_ssh_user" {}
variable "development_workstation_update_git_remotes_to_ssh" {}
variable "development_workstation_zone" {}
variable "google_organization_id" {}
variable "google_project_id" {}
variable "terraform_environment_configuration_directory_path" {}
