---
- name: Reload the systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Configure OS services
  ansible.builtin.systemd:
    name: "{{ item.service_name }}"
    state: "{{ item.service_state | default(omit) }}"
    enabled: "{{ item.enabled }}"
  with_items: "{{ os_services }}"
  register: stop_os_service
  # Services to stop might not exist, so we don't fail in that case
  failed_when:
    - stop_os_service.failed == true
    - '"Could not find the requested service" not in stop_os_service.msg'

- name: Debug stop_os_service
  ansible.builtin.debug:
    var: stop_os_service
    verbosity: 1
