---
- name: Add the DNS records defined for other hosts to the list of DNS records to configure
  ansible.builtin.set_fact:
    dns_records_to_configure: "{{ dns_records_to_configure + hostvars[item].dns_records_to_configure }}"
  when:
    # Exclude the current host because we have direct access to its dns_records_to_configure
    - inventory_hostname != item
    - hostvars[item].dns_records_to_configure is defined
  with_items: "{{ groups['all'] }}"

- name: Remove duplicates from the list of DNS records to configure
  ansible.builtin.set_fact:
    dns_records_to_configure: "{{ dns_records_to_configure | unique | sort(attribute='source,query_type,destination') }}"

- name: Debug dns_records_to_configure
  ansible.builtin.debug:
    var: dns_records_to_configure
    verbosity: 1
