---
- name: Get Raspberry Pi i2c status
  ansible.builtin.command: "raspi-config nonint get_i2c"
  become: true
  changed_when: false
  register: raspi_config_i2c_output

- name: Debug i2c status command output
  ansible.builtin.debug:
    var: raspi_config_i2c_output
    verbosity: 1

- name: Enable i2c
  ansible.builtin.command: "raspi-config nonint do_i2c 0"
  become: true
  changed_when: enable_i2c_output.stdout == "0"
  register: enable_i2c_output
  when: raspi_config_i2c_output.stdout != "0"

- name: Get Raspberry Pi serial status
  ansible.builtin.command: "raspi-config nonint get_serial"
  become: true
  changed_when: false
  register: raspi_config_serial_output

- name: Debug serial status command output
  ansible.builtin.debug:
    var: raspi_config_serial_output
    verbosity: 1

- name: Enable serial
  ansible.builtin.command: "raspi-config nonint do_serial 0"
  become: true
  changed_when: enable_serial_output.stdout == "0"
  register: enable_serial_output
  when: raspi_config_serial_output.stdout != "0"
