---
- name: Uninstall Debian packages
  ansible.builtin.apt:
    name: "{{ debian_packages_to_uninstall | default([]) }}"
    purge: true
    state: absent
    update_cache: true
  become: true
  when: ("uninstall-debian-packages" in ansible_run_tags or "all" in ansible_run_tags)

- name: Setup APT repository keys
  ansible.builtin.apt_key:
    keyring: "{{ item.repository_key_keyring_file_path }}"
    state: "{{ item.state | default(omit) }}"
    url: "{{ item.repository_key_url }}"
  become: true
  with_items: "{{ apt_repositories | unique }}"

- name: Setup APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repository_url }}"
    state: "{{ item.state | default(omit) }}"
  become: true
  with_items: "{{ apt_repositories | unique }}"

- name: Update APT package index, upgrade, autoclean, autoremove APT packages
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
    update_cache: true
    upgrade: true
  become: true

- name: Install Debian packages
  ansible.builtin.apt:
    cache_valid_time: "{{ apt_cache_valid_time }}"
    name: "{{ debian_packages_to_install | default([]) }}"
    state: present
    update_cache: true
  become: true
  when: ("install-debian-packages" in ansible_run_tags or "all" in ansible_run_tags)
