---
- name: "Delete {{ systemd_journal_file_path }}"
  ansible.builtin.file:
    path: "{{ systemd_journal_file_path }}"
    state: absent
  notify: Restart journald
  when: delete_systemd_journal_file
