---
- name: "Configure {{ raspberry_pi_config_file_path }}"
  ansible.builtin.lineinfile:
    line: "{{ item.key }}={{ item.value }}"
    dest: "{{ raspberry_pi_config_file_path }}"
    regexp: "^{{ item.key }}="
  notify: Reboot host and wait for it to restart
  with_dict: "{{ raspberry_pi_config_file_values }}"

# Helps avoiding overflowing dhcpcd because it tries to configure virtual network
# interfaces that Docker sets up for running containers.
# A few (potentially) related fixes are in dhcpcd 9.2.0, but Raspberry Pi OS
# is stuck at dhcpcd 8.1.2
# Ref: https://github.com/raspberrypi/linux/issues/4092
- name: "Configure dhcpcd to ignore Docker virtual network interfaces"
  ansible.builtin.lineinfile:
    line: "denyinterfaces veth*"
    path: /etc/dhcpcd.conf
  notify: Restart dhcpcd
