---
- name: Setup OS groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ os_groups }}"

- name: Setup OS users
  ansible.builtin.user:
    append: "{{ item.append | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    create_home: "{{ item.create_home | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    password_lock: "{{ item.password_lock | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
  with_items: "{{ os_users }}"

- name: Check if sudoers config file exists
  ansible.builtin.stat:
    path: "{{ sudoers_configuration_file_path }}"
  register: sudoers_file_stat_result

- name: Add configured user accounts to passwordless sudoers
  ansible.builtin.lineinfile:
    dest: "{{ sudoers_configuration_file_path }}"
    regexp: "^{{ item }}"
    line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"
    mode: "0440"
  with_items: "{{ security_sudoers_passwordless }}"
  when:
    - sudoers_file_stat_result.stat.exists

- name: Add configured user accounts to passworded sudoers
  ansible.builtin.lineinfile:
    dest: "{{ sudoers_configuration_file_path }}"
    regexp: "^{{ item }}"
    line: "{{ item }} ALL=(ALL) ALL"
    state: present
    validate: "visudo -cf %s"
    mode: "0440"
  with_items: "{{ security_sudoers_passworded }}"
  when:
    - sudoers_file_stat_result.stat.exists

- name: Create a directory for OpenSSH configuration - {{ ansible_user }}
  ansible.builtin.file:
    path: "{{ ansible_user_ssh_configuration_directory_path }}"
    state: directory
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0700"
  when:
    - configure_openssh_keypair

- name: Generate an OpenSSH keypair - {{ ansible_user }}
  community.crypto.openssh_keypair:
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    path: "{{ ansible_user_ssh_configuration_directory_path }}/id_rsa"
  when:
    - configure_openssh_keypair
