version: '3.5'
services:
  dnsmasq:
    container_name: dnsmasq
    hostname: dnsmasq
    image: ferrarimarco/home-lab-dnsmasq:1.2.1
    network_mode: "host"
    privileged: true
    restart_policy:
      condition: any
      delay: 10s
      window: 120s
    volumes:
      - "/etc/dnsmasq-home-lab/dhcp-hosts/host-configuration.conf:/etc/dhcp-hosts/host-configuration.conf"