---
version: '3.5'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn:latest
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ovpn-data-vpn-ferrarimarco-info:/etc/openvpn
