{
 "title": "SMARTmon",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disks",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by (device_model, disk, firmware_version, model_family, serial_number, type) (smartmon_device_info{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Active disks",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "smartmon_device_active{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Rolling average rate in load cycles per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(rate(smartmon_load_cycle_count_raw_value{instance=\"$node\",job=\"$job\"}[$__rate_interval])) by (disk)"
    }
   ]
  }
 ]
}