---
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
docs_dir: /docs
site_dir: /dest
site_name: Marco Ferrari
site_url: https://ferrarimarco.info
strict: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.top
    - navigation.tracking
    - toc.follow

extra:
  analytics:
    provider: google
    property: UA-18832248-1
  social:
    - icon: /fontawesome/regular/envelope
      name: send me an email
      link: mailto:ferrari.marco@gmail.com
    - icon: fontawesome/brands/github
      name: GitHub
      link: https://github.com/ferrarimarco
    - icon: fontawesome/brands/linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/ferrarimark
    - icon: fontawesome/brands/stack-overflow
      name: Stackoverflow
      link: https://stackoverflow.com/users/653462

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - blog
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      use_git: false
  - tags
