---
argonone_configuration_directories:
  - "{{ argonone_configuration_directory }}"
argonone_configuration_directories_to_copy:
  - src: "config/argonone-case/etc/argonone"
    dest: "{{ argonone_configuration_directory }}"
    os_services_to_restart:
      - "{{ argonone_os_service_name }}"
  - src: "config/argonone-case/lib/systemd/system"
    dest: "{{ systemd_system_services_configuration_directory }}"
    os_services_to_restart:
      - "{{ argonone_os_service_name }}"
  - src: "config/argonone-case/lib/systemd/system-shutdown"
    dest: "{{ systemd_system_shutdown_configuration_directory }}"
    os_services_to_restart:
      - "{{ argonone_os_service_name }}"
  - src: "config/argonone-case/usr/local/bin"
    dest: "/usr/local/bin"
    os_services_to_restart:
      - "{{ argonone_os_service_name }}"
argonone_configuration_directory: "{{ etc_directory_path }}/argonone-case"
argonone_os_services_to_configure:
  - enabled: true
    service_name: "{{ argonone_os_service_name }}"
    service_state: started
configuration_directories_to_copy: []
configuration_directories_to_create:
  - "{{ home_lab_configuration_directory_path }}"
  - "{{ systemd_configuration_directory }}"
  - "{{ systemd_journald_configuration_directory_path }}"
directories_to_ensure_ownership:
  - "{{ etc_directory_path }}"
default_docker_compose_file_name: "compose.yaml"
default_prometheus_configuration_file_name: "prometheus.yaml"
docker_compose_up_items: []
docker_compose_services_to_restart: []
docker_configuration_directories:
  - "{{ docker_daemon_configuration_directory_path }}"
docker_daemon_configuration_directory_path: "{{ etc_directory_path }}/docker"
docker_os_services_to_configure:
  - enabled: true
    service_name: "{{ docker_service_name }}"
    service_state: started
docker_repository_url: https://download.docker.com/linux
dphys_swapfile_templates_to_render:
  - src: "dphys-swapfile/dphys-swapfile.jinja"
    dest: "{{ etc_directory_path }}/dphys-swapfile"
    os_services_to_restart:
      - "{{ dphys_swapfile_service_name }}"
etc_directory_path: "/etc"
fail2ban_configuration_directory: "{{ etc_directory_path }}/fail2ban"
fail2ban_os_services_to_configure:
  - enabled: true
    service_name: "{{ fail2ban_service_name }}"
    service_state: started
fail2ban_templates_to_render:
  - src: "{{ security_fail2ban_custom_configuration_template }}"
    dest: "{{ fail2ban_configuration_directory }}/jail.local"
    os_services_to_restart:
      - "{{ fail2ban_service_name }}"
files_to_download: []
frigate_configuration_app_configuration_directory_path: "{{ frigate_configuration_directory_path }}/config"
frigate_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/frigate"
frigate_configuration_directories:
  - "{{ frigate_configuration_directory_path }}"
  # Create this because we only have templates to render
  - "{{ frigate_configuration_app_configuration_directory_path }}"
frigate_docker_compose_up_items:
  - compose_file_path: "{{ frigate_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
frigate_templates_to_render:
  - src: "frigate/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ frigate_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ frigate_docker_compose_up_items }}"
  - src: "frigate/config/config.yaml.jinja"
    dest: "{{ frigate_configuration_app_configuration_directory_path }}/config.yaml"
    docker_compose_services_to_restart: "{{ frigate_docker_compose_up_items }}"
home_assistant_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/home-assistant"
home_assistant_configuration_directories:
  - "{{ home_assistant_configuration_directory_path }}"
home_assistant_configuration_directories_to_copy:
  - src: "config/home-assistant"
    dest: "{{ home_assistant_configuration_directory_path }}"
    docker_compose_services_to_restart: "{{ home_assistant_docker_compose_up_items }}"
home_assistant_docker_compose_up_items:
  - compose_file_path: "{{ home_assistant_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
home_assistant_templates_to_render:
  - src: "home-assistant/config/configuration.yaml.jinja"
    dest: "{{ home_assistant_configuration_directory_path }}/config/configuration.yaml"
    docker_compose_services_to_restart: "{{ home_assistant_docker_compose_up_items }}"
home_lab_configuration_directory_path: "{{ etc_directory_path }}/ferrarimarco-home-lab"
monitoring_backend_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/monitoring-backend"
monitoring_backend_configuration_directories:
  - "{{ monitoring_backend_configuration_directory_path }}"
monitoring_backend_configuration_directories_to_copy:
  - src: "{{ monitoring_backend_configuration_source_directory_path }}"
    dest: "{{ monitoring_backend_configuration_directory_path }}"
    docker_compose_services_to_restart: "{{ monitoring_backend_docker_compose_up_items }}"
monitoring_backend_configuration_source_directory_path: "config/monitoring-backend"
monitoring_backend_default_dns_check_targets:
  - "{{ main_dns_server_address }}"
monitoring_backend_dns_a_record_check_template:
  - check_name: "dns_{{ item | lower | replace('.', '_') }}_a"
    query_name: "{{ item }}"
    query_type: "A"
monitoring_backend_docker_compose_up_items:
  - compose_file_path: "{{ monitoring_backend_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
monitoring_backend_templates_to_render:
  - src: "prometheus/{{ default_prometheus_configuration_file_name }}.jinja"
    dest: "{{ monitoring_backend_configuration_directory_path }}/{{ default_prometheus_configuration_file_name }}"
    docker_compose_services_to_restart: "{{ monitoring_backend_docker_compose_up_items }}"
  - src: "prometheus-blackbox-exporter/config.yaml.jinja"
    dest: "{{ monitoring_backend_configuration_directory_path }}/prometheus-blackbox-exporter-config.yaml"
    docker_compose_services_to_restart: "{{ monitoring_backend_docker_compose_up_items }}"
monitoring_configuration_directories:
  - "{{ monitoring_configuration_directory_path }}"
  - "{{ monitoring_host_metrics_directory_path }}"
monitoring_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/monitoring"
monitoring_docker_compose_up_items:
  - compose_file_path: "{{ monitoring_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
monitoring_host_metrics_directory_path: "/var/lib/node_exporter/textfile_collector"
monitoring_prometheus_node_exporter_textfile_collector_directory: "/var/lib/node_exporter/textfile_collector"
monitoring_smartmon_prometheus_exporter_script_destination_path: "/usr/local/bin/node-exporter-text-smartmon"
monitoring_smartmon_prometheus_exporter_service_name: "smartmon-prometheus-exporter"
monitoring_smartmon_prometheus_exporter_service_file_name: "{{ monitoring_smartmon_prometheus_exporter_service_name }}.service"
monitoring_smartmon_prometheus_exporter_timer_file_name: "{{ monitoring_smartmon_prometheus_exporter_service_name }}.timer"
monitoring_templates_to_render:
  - src: "monitoring/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ monitoring_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ monitoring_docker_compose_up_items }}"
  - src: "monitoring/{{ monitoring_smartmon_prometheus_exporter_service_file_name }}.jinja"
    dest: "{{ systemd_system_services_configuration_directory }}/{{ monitoring_smartmon_prometheus_exporter_service_file_name }}"
    os_services_to_restart:
      - "{{ monitoring_smartmon_prometheus_exporter_service_name }}"
  - src: "monitoring/{{ monitoring_smartmon_prometheus_exporter_timer_file_name }}.jinja"
    dest: "{{ systemd_system_services_configuration_directory }}/{{ monitoring_smartmon_prometheus_exporter_timer_file_name }}"
    os_services_to_restart:
      - "{{ monitoring_smartmon_prometheus_exporter_service_name }}"
mosquitto_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/mosquitto"
mosquitto_configuration_directories:
  - "{{ mosquitto_configuration_directory_path }}"
mosquitto_configuration_directories_to_copy:
  - src: "config/mosquitto"
    dest: "{{ mosquitto_configuration_directory_path }}"
    docker_compose_services_to_restart: "{{ mosquitto_docker_compose_up_items }}"
mosquitto_docker_compose_up_items:
  - compose_file_path: "{{ mosquitto_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
os_groups_to_create: []
os_services_to_configure: []
os_services_to_restart: []
os_users_to_create:
  # Add the default user groups to ansible_user
  # Don't lock the password here because we want to be sure to set up key-based authentication first
  - append: true
    name: "{{ ansible_user }}"
    groups: "{{ default_user_groups }}"
samba_service_name: "smbd"
sense_hat_exporter_configuration_directories:
  - "{{ sense_hat_exporter_configuration_directory_path }}"
sense_hat_exporter_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/sense-hat-exporter"
sense_hat_exporter_configuration_directories_to_copy:
  - src: "config/sense-hat-exporter"
    dest: "{{ sense_hat_exporter_configuration_directory_path }}"
    os_services_to_restart:
      - "{{ sense_hat_exporter_os_service_name }}"
sense_hat_exporter_executable_path: "{{ sense_hat_exporter_configuration_directory_path }}/sense-hat-exporter.py"
sense_hat_exporter_requirements_file_path: "{{ sense_hat_exporter_configuration_directory_path }}/requirements.txt"
sense_hat_exporter_run_directory_path: "/run/sense-hat-exporter"
sense_hat_exporter_virtual_env_path: "{{ sense_hat_exporter_run_directory_path }}/.venv"
sense_hat_exporter_os_service_file_name: "{{ sense_hat_exporter_os_service_name }}.service"
sense_hat_exporter_os_service_name: "sense-hat-exporter"
sense_hat_os_services_to_configure:
  - enabled: true
    service_name: "{{ sense_hat_exporter_os_service_file_name }}"
    service_state: started
sense_hat_templates_to_render:
  - src: "sense-hat-exporter/{{ sense_hat_exporter_os_service_file_name }}.jinja"
    dest: "{{ systemd_system_services_configuration_directory }}/{{ sense_hat_exporter_os_service_file_name }}"
    os_services_to_restart:
      - "{{ sense_hat_exporter_os_service_name }}"
ssh_os_services_to_configure:
  - enabled: true
    service_name: "{{ security_sshd_name }}"
    service_state: started
sshd_validation_command: "{{ sshd_path }} -T -f %s"
systemd_configuration_directory: /etc/systemd
systemd_system_services_configuration_directory: "{{ systemd_configuration_directory }}/system"
systemd_system_shutdown_configuration_directory: "{{ systemd_configuration_directory }}/system-shutdown"
systemd_journald_configuration_directory_path: "{{ systemd_configuration_directory + '/journald.conf.d' }}"
systemd_journal_file_path: /var/log/journal
tailscale_base_package_repository_url: "https://pkgs.tailscale.com/{{ tailscale_release_channel }}"
templates_to_render:
  - src: "systemd/journald/001-journald.conf.jinja"
    dest: "{{ systemd_journald_configuration_directory_path }}/001-journald.conf"
    os_services_to_restart:
      - systemd-journald
torrent_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/qbittorrent"
torrent_configuration_directories:
  - "{{ torrent_configuration_directory_path }}"
torrent_configuration_directories_to_copy:
  - src: "config/qbittorrent"
    dest: "{{ torrent_configuration_directory_path }}"
    docker_compose_services_to_restart: "{{ torrent_docker_compose_up_items }}"
torrent_docker_compose_up_items:
  - compose_file_path: "{{ torrent_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
torrent_templates_to_render:
  - src: "qbittorrent/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ torrent_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ torrent_docker_compose_up_items }}"
unattended_upgrades_os_services_to_configure:
  - enabled: true
    service_name: "{{ unattended_upgrades_service_name }}"
    service_state: started
unattended_upgrades_templates_to_render:
  - src: "unattended-upgrades/20auto-upgrades.jinja"
    dest: "{{ etc_directory_path }}/apt/apt.conf.d/20auto-upgrades"
    os_services_to_restart:
      - "{{ unattended_upgrades_service_name }}"
zigbee2mqtt_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/zigbee2mqtt"
zigbee2mqtt_configuration_directories:
  - "{{ zigbee2mqtt_configuration_directory_path }}"
  - "{{ zigbee2mqtt_configuration_directory_path }}/data"
zigbee2mqtt_docker_compose_up_items:
  - compose_file_path: "{{ zigbee2mqtt_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
zigbee2mqtt_templates_to_render:
  - src: "zigbee2mqtt/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ zigbee2mqtt_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ zigbee2mqtt_docker_compose_up_items }}"
  - src: "zigbee2mqtt/data/configuration.yaml.jinja"
    dest: "{{ zigbee2mqtt_configuration_directory_path }}/data/configuration.yaml"
    docker_compose_services_to_restart: "{{ zigbee2mqtt_docker_compose_up_items }}"
  - src: "zigbee2mqtt/data/secret.yaml.jinja"
    dest: "{{ zigbee2mqtt_configuration_directory_path }}/data/secret.yaml"
    docker_compose_services_to_restart: "{{ zigbee2mqtt_docker_compose_up_items }}"
    # Don't force template rendering for secrets.yaml because zigbee2mqtt modifies this file at runtime to store the generate network key
    force: false
...
