---
configuration_directories_to_copy: []
configuration_directories_to_create:
  - "{{ home_lab_configuration_directory_path }}"
  - "{{ systemd_configuration_directory }}"
  - "{{ systemd_journald_configuration_directory_path }}"
directories_to_ensure_ownership:
  - "{{ etc_directory_path }}"
default_docker_compose_file_name: "compose.yaml"
default_prometheus_configuration_file_name: "prometheus.yaml"
docker_compose_up_items: []
docker_daemon_configuration_directory_path: "{{ etc_directory_path }}/docker"
docker_repository_url: https://download.docker.com/linux
etc_directory_path: "/etc"
home_lab_configuration_directory_path: "{{ etc_directory_path }}/ferrarimarco-home-lab"
monitoring_backend_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/monitoring-backend"
monitoring_backend_configuration_directories:
  - "{{ monitoring_backend_configuration_directory_path }}"
monitoring_backend_configuration_directories_to_copy:
  - src: "{{ monitoring_backend_configuration_source_directory_path }}"
    dest: "{{ monitoring_backend_configuration_directory_path }}"
monitoring_backend_configuration_source_directory_path: "config/monitoring-backend"
monitoring_backend_docker_compose_up_items:
  - compose_file_path: "{{ monitoring_backend_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
monitoring_backend_templates_to_render:
  - src: "prometheus/{{ default_prometheus_configuration_file_name }}.jinja"
    dest: "{{ monitoring_backend_configuration_directory_path }}/{{ default_prometheus_configuration_file_name }}"
monitoring_configuration_directories:
  - "{{ monitoring_configuration_directory_path }}"
monitoring_configuration_directories_to_copy:
  - src: "{{ monitoring_configuration_source_directory_path }}"
    dest: "{{ monitoring_configuration_directory_path }}"
monitoring_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/monitoring"
monitoring_configuration_source_directory_path: "config/monitoring"
monitoring_docker_compose_up_items:
  - compose_file_path: "{{ monitoring_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
sshd_validation_command: "{{ sshd_path }} -T -f %s"
systemd_configuration_directory: /etc/systemd
systemd_journald_configuration_directory_path: "{{ systemd_configuration_directory + '/journald.conf.d' }}"
systemd_journal_file_path: /var/log/journal
templates_to_render: []
...
