---
configuration_directories_to_copy: []
configuration_directories_to_create:
  - "{{ home_lab_configuration_directory_path }}"
docker_repository_url: https://download.docker.com/linux
home_lab_configuration_directory_path: /etc/ferrarimarco-home-lab
monitoring_configuration_directories:
  - "{{ monitoring_configuration_directory_path }}"
monitoring_configuration_directories_to_copy:
  - src: "{{ monitoring_configuration_source_directory_path }}"
    dest: "{{ monitoring_configuration_directory_path }}"
monitoring_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/monitoring"
monitoring_configuration_source_directory_path: "config/monitoring"
sshd_validation_command: "{{ sshd_path }} -T -f %s"
systemd_configuration_directory: /etc/systemd
systemd_journald_configuration_directory_path: "{{ systemd_configuration_directory + '/journald.conf.d' }}"
systemd_journal_file_path: /var/log/journal
...
