---
argonone_configuration_directories:
  - path: "{{ argonone_configuration_directory }}"
argonone_configuration_directories_to_copy:
  - src: "config/argonone-case/etc/argonone"
    dest: "{{ argonone_configuration_directory }}"
    os_services_to_restart:
      - "{{ argonone_os_service_name }}"
  - src: "config/argonone-case/lib/systemd/system"
    dest: "{{ systemd_system_services_configuration_directory }}"
    os_services_to_restart:
      - "{{ argonone_os_service_name }}"
  - src: "config/argonone-case/lib/systemd/system-shutdown"
    dest: "{{ systemd_system_shutdown_configuration_directory }}"
    os_services_to_restart:
      - "{{ argonone_os_service_name }}"
  - src: "config/argonone-case/usr/local/bin"
    dest: "/usr/local/bin"
    os_services_to_restart:
      - "{{ argonone_os_service_name }}"
argonone_configuration_directory: "{{ etc_directory_path }}/argonone-case"
argonone_os_services_to_configure:
  - enabled: true
    service_name: "{{ argonone_os_service_name }}"
    service_state: started
configuration_directories_to_copy: []
configuration_directories_to_create:
  - path: "{{ home_lab_configuration_directory_path }}"
  - path: "{{ systemd_configuration_directory }}"
  - path: "{{ systemd_journald_configuration_directory_path }}"
cron_jobs: []
directories_to_ensure_ownership:
  - "{{ etc_directory_path }}"
default_docker_compose_file_name: "compose.yaml"
default_prometheus_configuration_file_name: "prometheus.yaml"
docker_compose_up_items: []
docker_compose_services_to_restart: []
docker_configuration_directories:
  - path: "{{ docker_daemon_configuration_directory_path }}"
docker_daemon_configuration_directory_path: "{{ etc_directory_path }}/docker"
docker_daemon_configuration_file_name: "daemon.json"
docker_os_services_to_configure:
  - enabled: true
    service_name: "{{ docker_service_name }}"
    service_state: started
docker_repository_url: https://download.docker.com/linux
docker_templates_to_render:
  - src: "docker/{{ docker_daemon_configuration_file_name }}.jinja"
    dest: "{{ docker_daemon_configuration_directory_path }}/daemon.json"
    os_services_to_restart:
      - "{{ docker_service_name }}"
dphys_swapfile_templates_to_render:
  - src: "dphys-swapfile/dphys-swapfile.jinja"
    dest: "{{ etc_directory_path }}/dphys-swapfile"
    os_services_to_restart:
      - "{{ dphys_swapfile_service_name }}"
etc_directory_path: "/etc"
fail2ban_configuration_directory: "{{ etc_directory_path }}/fail2ban"
fail2ban_os_services_to_configure:
  - enabled: true
    service_name: "{{ fail2ban_service_name }}"
    service_state: started
fail2ban_templates_to_render:
  - src: "{{ security_fail2ban_custom_configuration_template }}"
    dest: "{{ fail2ban_configuration_directory }}/jail.local"
    os_services_to_restart:
      - "{{ fail2ban_service_name }}"
files_to_download: []
files_to_remove: []
frigate_configuration_app_configuration_directory_path: "{{ frigate_configuration_directory_path }}/config"
frigate_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/frigate"
frigate_configuration_directories:
  - path: "{{ frigate_configuration_directory_path }}"
  - path: "{{ frigate_configuration_app_configuration_directory_path }}"
frigate_docker_compose_up_items:
  - compose_file_path: "{{ frigate_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
frigate_templates_to_render:
  - src: "frigate/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ frigate_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ frigate_docker_compose_up_items }}"
  - src: "frigate/config/config.yaml.jinja"
    dest: "{{ frigate_configuration_app_configuration_directory_path }}/config.yaml"
    docker_compose_services_to_restart: "{{ frigate_docker_compose_up_items }}"
home_assistant_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/home-assistant"
home_assistant_configuration_directories:
  - path: "{{ home_assistant_configuration_directory_path }}"
  - path: "{{ home_assistant_configuration_directory_path }}/config"
home_assistant_docker_compose_up_items:
  - compose_file_path: "{{ home_assistant_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
home_assistant_templates_to_render:
  - src: "home-assistant/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ home_assistant_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ home_assistant_docker_compose_up_items }}"
  - src: "home-assistant/config/automations.yaml.jinja"
    dest: "{{ home_assistant_configuration_directory_path }}/config/automations.yaml"
    docker_compose_services_to_restart: "{{ home_assistant_docker_compose_up_items }}"
  - src: "home-assistant/config/configuration.yaml.jinja"
    dest: "{{ home_assistant_configuration_directory_path }}/config/configuration.yaml"
    docker_compose_services_to_restart: "{{ home_assistant_docker_compose_up_items }}"
  - src: "home-assistant/config/secrets.yaml.jinja"
    dest: "{{ home_assistant_configuration_directory_path }}/config/secrets.yaml"
    docker_compose_services_to_restart: "{{ home_assistant_docker_compose_up_items }}"
    force: false
home_lab_configuration_directory_path: "{{ etc_directory_path }}/ferrarimarco-home-lab"
monitoring_backend_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/monitoring-backend"
monitoring_backend_configuration_directories:
  - path: "{{ monitoring_backend_configuration_directory_path }}"
monitoring_backend_configuration_directories_to_copy:
  - src: "{{ monitoring_backend_configuration_source_directory_path }}"
    dest: "{{ monitoring_backend_configuration_directory_path }}"
    docker_compose_services_to_restart: "{{ monitoring_backend_docker_compose_up_items }}"
monitoring_backend_configuration_source_directory_path: "config/monitoring-backend"
monitoring_backend_dns_a_record_check_template_for_ansible_hosts:
  - check_name: "dns_{{ item | lower | replace('.', '_') }}_a"
    query_name: "{{ item }}"
    query_type: "A"
monitoring_backend_dns_check_target_template:
  - "{{ item.fqdn }}"
  - "{{ item.ipv4_address }}"
monitoring_backend_dns_record_check_template:
  - check_name: "dns_{{ item.source | lower | replace('.', '_') }}_{{ item.query_type|lower }}"
    query_name: "{{ item.source }}"
    query_type: "{{ item.query_type }}"
monitoring_backend_http_cadvisor_endpoint_check_template:
  - check_target: "http://{{ item }}:{{ cadvisor_exposed_port }} # cAdvisor"
monitoring_backend_http_prometheus_node_exporter_endpoint_check_template:
  - check_target: "http://{{ item }}:{{ prometheus_node_exporter_port }} # Prometheus Node Exporter"
monitoring_backend_docker_compose_up_items:
  - compose_file_path: "{{ monitoring_backend_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
monitoring_backend_templates_to_render:
  - src: "monitoring-backend/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ monitoring_backend_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ monitoring_backend_docker_compose_up_items }}"
  - src: "prometheus/{{ default_prometheus_configuration_file_name }}.jinja"
    dest: "{{ monitoring_backend_configuration_directory_path }}/{{ default_prometheus_configuration_file_name }}"
    docker_compose_services_to_restart: "{{ monitoring_backend_docker_compose_up_items }}"
  - src: "prometheus-blackbox-exporter/config.yaml.jinja"
    dest: "{{ monitoring_backend_configuration_directory_path }}/prometheus-blackbox-exporter-config.yaml"
    docker_compose_services_to_restart: "{{ monitoring_backend_docker_compose_up_items }}"
monitoring_configuration_directories:
  - path: "{{ monitoring_configuration_directory_path }}"
  - path: "{{ monitoring_host_metrics_directory_path }}"
monitoring_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/monitoring"
monitoring_docker_compose_up_items:
  - compose_file_path: "{{ monitoring_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
monitoring_host_metrics_directory_path: "/var/lib/node_exporter/textfile_collector"
monitoring_prometheus_node_exporter_textfile_collector_directory: "/var/lib/node_exporter/textfile_collector"
monitoring_smartmon_prometheus_exporter_script_destination_path: "/usr/local/bin/node-exporter-text-smartmon"
monitoring_smartmon_prometheus_exporter_service_name: "smartmon-prometheus-exporter"
monitoring_smartmon_prometheus_exporter_service_file_name: "{{ monitoring_smartmon_prometheus_exporter_service_name }}.service"
monitoring_smartmon_prometheus_exporter_timer_file_name: "{{ monitoring_smartmon_prometheus_exporter_service_name }}.timer"
monitoring_templates_to_render:
  - src: "monitoring/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ monitoring_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ monitoring_docker_compose_up_items }}"
  - src: "monitoring/{{ monitoring_smartmon_prometheus_exporter_service_file_name }}.jinja"
    dest: "{{ systemd_system_services_configuration_directory }}/{{ monitoring_smartmon_prometheus_exporter_service_file_name }}"
    os_services_to_restart:
      - "{{ monitoring_smartmon_prometheus_exporter_service_name }}"
  - src: "monitoring/{{ monitoring_smartmon_prometheus_exporter_timer_file_name }}.jinja"
    dest: "{{ systemd_system_services_configuration_directory }}/{{ monitoring_smartmon_prometheus_exporter_timer_file_name }}"
    os_services_to_restart:
      - "{{ monitoring_smartmon_prometheus_exporter_service_name }}"
mosquitto_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/mosquitto"
# The mosquitto container image creates a user with the specified uid and gid that takes owenership of the configuration directory.
# Ansible may emit a warning because a user with such ids doesn't exist on the system, but it does in the container.
mosquitto_user_group_id: "1883"
mosquitto_user_user_id: "1883"
mosquitto_configuration_directories:
  - path: "{{ mosquitto_configuration_directory_path }}"
  - group: "{{ mosquitto_user_group_id }}"
    owner: "{{ mosquitto_user_user_id }}"
    path: "{{ mosquitto_configuration_directory_path }}/config"
mosquitto_docker_compose_up_items:
  - compose_file_path: "{{ mosquitto_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
mosquitto_templates_to_render:
  - src: "mosquitto/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ mosquitto_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ mosquitto_docker_compose_up_items }}"
  - src: "mosquitto/config/mosquitto.conf.jinja"
    dest: "{{ mosquitto_configuration_directory_path }}/config/mosquitto.conf"
    docker_compose_services_to_restart: "{{ mosquitto_docker_compose_up_items }}"
    group: "{{ mosquitto_user_group_id }}"
    owner: "{{ mosquitto_user_user_id }}"
network_stack_configuration_directories:
  - path: "{{ network_stack_configuration_directory_path }}"
  - path: "{{ network_stack_configuration_directory_path }}/coredns"
  - path: "{{ network_stack_configuration_directory_path }}/coredns/zones"
network_stack_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/network-stack"
network_stack_dns_a_records_to_configure_for_root_dns_template:
  - source: "{{ item.fqdn }}"
    destination: "{{ item.ipv4_address }}"
    query_type: A
network_stack_dns_aaaa_records_to_configure_for_root_dns_template:
  - source: "{{ item.fqdn }}"
    destination: "{{ item.ipv6_address }}"
    query_type: AAAA
network_stack_docker_compose_up_items:
  - compose_file_path: "{{ network_stack_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
network_stack_templates_to_render:
  - src: "network-stack/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ network_stack_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ network_stack_docker_compose_up_items }}"
  - src: "network-stack/coredns/Corefile.jinja"
    dest: "{{ network_stack_configuration_directory_path }}/coredns/Corefile"
    docker_compose_services_to_restart: "{{ network_stack_docker_compose_up_items }}"
  - src: "network-stack/coredns/zones/{{ root_fqdn }}.jinja"
    dest: "{{ network_stack_configuration_directory_path }}/coredns/zones/{{ root_fqdn }}"
    docker_compose_services_to_restart: "{{ network_stack_docker_compose_up_items }}"
os_groups_to_create: []
os_services_to_configure: []
os_services_to_restart: []
os_users_to_create:
  # Add the default user groups to ansible_user
  # Don't lock the password here because we want to be sure to set up key-based authentication first
  - append: true
    name: "{{ ansible_user }}"
    groups: "{{ default_user_groups }}"
prometheus_node_exporter_port: 9100
samba_service_name: "smbd"
sense_hat_exporter_configuration_directories:
  - path: "{{ sense_hat_exporter_configuration_directory_path }}"
sense_hat_exporter_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/sense-hat-exporter"
sense_hat_exporter_configuration_directories_to_copy:
  - src: "config/sense-hat-exporter"
    dest: "{{ sense_hat_exporter_configuration_directory_path }}"
    os_services_to_restart:
      - "{{ sense_hat_exporter_os_service_name }}"
sense_hat_exporter_executable_path: "{{ sense_hat_exporter_configuration_directory_path }}/sense-hat-exporter.py"
sense_hat_exporter_requirements_file_path: "{{ sense_hat_exporter_configuration_directory_path }}/requirements.txt"
sense_hat_exporter_run_directory_path: "/run/sense-hat-exporter"
sense_hat_exporter_virtual_env_path: "{{ sense_hat_exporter_run_directory_path }}/.venv"
sense_hat_exporter_os_service_file_name: "{{ sense_hat_exporter_os_service_name }}.service"
sense_hat_exporter_os_service_name: "sense-hat-exporter"
sense_hat_os_services_to_configure:
  - enabled: true
    service_name: "{{ sense_hat_exporter_os_service_file_name }}"
    service_state: started
sense_hat_templates_to_render:
  - src: "sense-hat-exporter/{{ sense_hat_exporter_os_service_file_name }}.jinja"
    dest: "{{ systemd_system_services_configuration_directory }}/{{ sense_hat_exporter_os_service_file_name }}"
    os_services_to_restart:
      - "{{ sense_hat_exporter_os_service_name }}"
ssh_os_services_to_configure:
  - enabled: true
    service_name: "{{ security_sshd_name }}"
    service_state: started
sshd_validation_command: "{{ sshd_path }} -T -f %s"
systemd_configuration_directory: /etc/systemd
systemd_system_services_configuration_directory: "{{ systemd_configuration_directory }}/system"
systemd_system_shutdown_configuration_directory: "{{ systemd_configuration_directory }}/system-shutdown"
systemd_journald_configuration_directory_path: "{{ systemd_configuration_directory + '/journald.conf.d' }}"
systemd_journal_file_path: /var/log/journal
tailscale_base_package_repository_url: "https://pkgs.tailscale.com/{{ tailscale_release_channel }}"
templates_to_render:
  - src: "systemd/journald/001-journald.conf.jinja"
    dest: "{{ systemd_journald_configuration_directory_path }}/001-journald.conf"
    os_services_to_restart:
      - systemd-journald
torrent_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/qbittorrent"
# The qbittorrent container image creates a user with the specified uid and gid that takes owenership of the configuration directory.
# Ansible may emit a warning because a user with such ids doesn't exist on the system, but it does in the container.
torrent_owner_group_id: "1000"
torrent_owner_user_id: "1000"
torrent_configuration_directories:
  - group: "{{ torrent_owner_group_id }}"
    owner: "{{ torrent_owner_user_id }}"
    path: "{{ torrent_configuration_directory_path }}"
torrent_docker_compose_up_items:
  - compose_file_path: "{{ torrent_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
torrent_templates_to_render:
  - src: "qbittorrent/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ torrent_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ torrent_docker_compose_up_items }}"
    group: "{{ torrent_owner_group_id }}"
    owner: "{{ torrent_owner_user_id }}"
  - src: "qbittorrent/qBittorrent.conf.jinja"
    dest: "{{ torrent_configuration_directory_path }}/qBittorrent.conf"
    docker_compose_services_to_restart: "{{ torrent_docker_compose_up_items }}"
    group: "{{ torrent_owner_group_id }}"
    owner: "{{ torrent_owner_user_id }}"
unattended_upgrades_os_services_to_configure:
  - enabled: true
    service_name: "{{ unattended_upgrades_service_name }}"
    service_state: started
unattended_upgrades_templates_to_render:
  - src: "unattended-upgrades/20auto-upgrades.jinja"
    dest: "{{ etc_directory_path }}/apt/apt.conf.d/20auto-upgrades"
    os_services_to_restart:
      - "{{ unattended_upgrades_service_name }}"
wifi_templates_to_render:
  - src: "wifi/wpa_supplicant.conf.jinja"
    dest: "{{ etc_directory_path }}/wpa_supplicant/wpa_supplicant.conf"
    mode: "0600"
    os_services_to_restart:
      - "{{ wpa_supplicant_service_name }}"
    # Don't force template rendering because the user might have manually changed the WiFi network credentials
    force: false
zigbee2mqtt_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/zigbee2mqtt"
zigbee2mqtt_configuration_directories:
  - path: "{{ zigbee2mqtt_configuration_directory_path }}"
  - path: "{{ zigbee2mqtt_configuration_directory_path }}/data"
zigbee2mqtt_docker_compose_up_items:
  - compose_file_path: "{{ zigbee2mqtt_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
zigbee2mqtt_templates_to_render:
  - src: "zigbee2mqtt/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ zigbee2mqtt_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
    docker_compose_services_to_restart: "{{ zigbee2mqtt_docker_compose_up_items }}"
  - src: "zigbee2mqtt/data/configuration.yaml.jinja"
    dest: "{{ zigbee2mqtt_configuration_directory_path }}/data/configuration.yaml"
    docker_compose_services_to_restart: "{{ zigbee2mqtt_docker_compose_up_items }}"
  - src: "zigbee2mqtt/data/secret.yaml.jinja"
    dest: "{{ zigbee2mqtt_configuration_directory_path }}/data/secret.yaml"
    docker_compose_services_to_restart: "{{ zigbee2mqtt_docker_compose_up_items }}"
    # Don't force template rendering because zigbee2mqtt modifies this file at runtime to store the generated network key
    force: false
...
