---
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-os-images'
    paths:
      - './*.xz'
options:
  machineType: 'N1_HIGHCPU_8'
steps:
  - id: 'Build the customized OS image'
    name: 'gcr.io/$PROJECT_ID/arm-image-builder:$_ARM_BUILDER_IMAGE_TAG'
    args:
      - "--entrypoint"
      - "$$(pwd)/build.sh"
      - "--options"
      - >-
        --build-config $$(pwd)/config/build.conf
        --cloud-init-meta-data $$(pwd)/$_CLOUD_INIT_META_DATA_CONFIG_PATH
        --cloud-init-network-config $$(pwd)/$_CLOUD_INIT_NETWORK_CONFIG_PATH
        --cloud-init-user-data $$(pwd)/$_CLOUD_INIT_USER_DATA_PATH
        --os-image-tag $_OS_IMAGE_TAG
substitutions:
  _ARM_BUILDER_IMAGE_TAG: 'ec9be07'
timeout: 37000s
