---
version: 2
ethernets:
  eth0:
    addresses:
      - 10.0.0.2/8
    dhcp4: false
    gateway4: 10.0.0.1
    nameservers:
      addresses:
        - 8.8.8.8
        - 8.8.4.4
      search:
        - edge.lab.ferrari.how
    optional: true
...
