#cloud-config
---
autoinstall:

  keyboard:
    layout: us
    toggle: null
    variant: ''

  network:
    version: 2
    ethernets:
      enp0s25:
        addresses:
          - 10.0.0.2/8
        dhcp4: false
        gateway4: 10.0.0.1
        nameservers:
          addresses:
            - 8.8.8.8
            - 8.8.4.4
          search:
            - edge.lab.ferrari.how
        optional: true

  ssh:
    allow-pw: false
    install-server: true

  storage:
    layout:
      name: lvm

  user-data:

    groups:
      - microk8s

    hostname: home-lab-1

    locale: "en_US.UTF-8"

    # update the contents of /etc/hosts based on the hostname/fqdn specified
    manage_etc_hosts: true

    # Set up the NTP client with default configuration and client
    ntp:
      enabled: true
      ntp_client: auto

    packages:
      - openssh-server

    package_update: true
    package_upgrade: true
    package_reboot_if_required: true

    random_seed:
      file: /dev/urandom
      command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
      command_required: true

    resize_rootfs: true

    # We don't use a script because Ubuntu autoinstall doesn't support generating
    # a user-data file that includes scripts that are not in autoinstall.user-data
    runcmd:
      - /snap/bin/microk8s status --wait-ready
      - /snap/bin/microk8s enable dashboard dns gpu ingress storage
      - /snap/bin/microk8s status --wait-ready

    snap:
      commands:
        "001": "snap install microk8s --classic --channel=1.23/stable"

    # Disable password authentication with the SSH daemon
    # for the default user
    ssh_pwauth: false

    # Remove default host keys if any
    ssh_deletekeys: true

    timezone: "Etc/UTC"

    # Create users and don't preserve the default user, so that we've full control on which accounts we expect to be there.
    # The cc_set_passwords module automatically expires passwords for all the users that cloud-init creates, so no need
    # to add a chpasswd configuration section.
    users:
      - name: marco
        gecos: Marco
        groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, microk8s, netdev, plugdev, sudo, video]
        lock_passwd: true
        shell: /usr/bin/bash
        sudo: ["ALL=(ALL) NOPASSWD:ALL"]

  version: 1
...
