---
extends: default

locale: "en_US.UTF-8"

rules:
  colons:
    max-spaces-after: 1
  comments:
    # cloud-init expects the first line to be #cloud-config and this conflicts with
    # the rules.comments.require-starting-space directive.
    # See https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments
    ignore: |
      **/cloud-init/**/user-data.yaml
      **/cloud-init/**/user-data-autoinstall.yaml
    level: error
  comments-indentation:
    level: error
  document-end:
    level: error
  document-start:
    level: error
  empty-values: enable
  line-length:
    allow-non-breakable-inline-mappings: true
    max: 250
  octal-values: enable
  truthy:
    level: error
...
