variable "beaglebone_black_ethernet_ipv4_address" {}
variable "cloud_build_service_account_id" {}
variable "cert_manager_chart_version" {}
variable "configuration_bucket_name" {}
variable "configuration_gke_cluster_node_pool_size" {}
variable "configuration_gke_cluster_subnet_ip_cidr_range" {}
variable "consul_chart_version" {}
variable "consul_datacenter_name" {}
variable "consul_template_directory_path" {}
variable "dns_record_sets_main_zone" {}
variable "edge_default_gateway_ipv4_address" {}
variable "edge_dns_zone" {}
variable "edge_external_dns_servers_primary" {}
variable "edge_external_dns_servers_secondary" {}
variable "edge_iot_core_registry_project_id" {}
variable "edge_iot_core_registry_id" {}
variable "edge_main_subnet_dhcp_lease_time" {}
variable "edge_main_subnet_ipv4_address_range_end" {}
variable "edge_main_subnet_ipv4_address_range_start" {}
variable "edge_main_subnet_ipv4_address" {}
variable "gke_version_prefix" {}
variable "google_compute_network_vpc_name" {}
variable "google_compute_subnetwork_vpc_name" {}
variable "google_organization_id" {}
variable "google_project_id" {}
variable "google_region" {}
variable "iot_core_initializer_container_image_id" {}
variable "iot_core_key_bits" {}
variable "iot_core_credentials_validity" {}
variable "main_dns_zone" {}
variable "mqtt_container_image_ic" {}
