variable "cloud_build_service_account_id" {}
variable "configuration_gke_cluster_node_pool_size" {}
variable "configuration_gke_cluster_subnet_ip_cidr_range" {}
variable "consul_chart_version" {}
variable "consul_datacenter_name" {}
variable "gke_version_prefix" {}
variable "google_organization_id" {}
variable "google_project_id" {}
variable "google_region" {}
variable "google_compute_network_vpc_name" {}
variable "google_compute_subnetwork_vpc_name" {}
variable "tls_self_signed_cert_ca_subject_common_name" {}
variable "tls_self_signed_cert_ca_subject_organization" {}
