---
ansible_python_interpreter: auto_silent
frigate_http_endpoint_fqdn: "raspberrypi2.edge.lab.ferrari.how"
grafana_http_endpoint_fqdn: "raspberrypi.edge.lab.ferrari.how"
home_assistant_http_endpoint_fqdn: "raspberrypi.edge.lab.ferrari.how"
prometheus_http_endpoint_fqdn: "raspberrypi.edge.lab.ferrari.how"
prometheus_blackbox_exporter_http_endpoint_fqdn: "raspberrypi.edge.lab.ferrari.how"
qbittorrent_http_endpoint_fqdn: "raspberrypi2.edge.lab.ferrari.how"
zigbee2mqtt_http_endpoint_fqdn: "raspberrypi2.edge.lab.ferrari.how"
mosquitto_server_fqdn: "raspberrypi2.edge.lab.ferrari.how"
...
