---
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
docs_dir: "../../../docs-src"
repo_url: https://github.com/ferrarimarco/home-lab
site_dir: "../../../docs"
site_name: Home Lab docs
site_url: https://ferrarimarco.github.io/home-lab
strict: true
theme:
  name: material
  features:
    - navigation.top
    - navigation.tracking
