---
image:
  repository: ${opentelemetry_collector_image_id}
  tag: ${opentelemetry_collector_image_tag}

command:
  extraArgs:
    - "--log-level=DEBUG"
  name: docker-entrypoint.sh

config:
  exporters:
    logging:
      loglevel: debug
    stackdriver: {}

  extensions:
    health_check: {}
    pprof: {}
    zpages: {}
  receivers:
    jaeger: null
    otlp: null
    prometheus:
      config:
        scrape_configs: ${jsonencode(prometheus_configuration)}
    zipkin: null
  service:
    extensions:
      - health_check
      - pprof
      - zpages
    pipelines:
      metrics:
        exporters:
          - logging
          - stackdriver
        receivers:
          - prometheus
      traces: null

# No need for an agent collector now
agentCollector:
  enabled: false

serviceAccount:
  annotations: ${jsonencode(service_account_annotations)}
  name: ${service_account_name}

# Enable the standalone collector
standaloneCollector:
  enabled: true
  replicaCount: 1
