---
exclude: |
  (?x)^(
      .*\.venv.*
  )$
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args:
          - "--unsafe"
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - "-c=config/lint/.yaml-lint.yml"
          - --strict
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.17.0
    hooks:
      - id: ansible-lint
        entry: "sh -c 'cd docker/ansible/etc/ansible && ansible-lint -c ../../../../config/lint/.ansible-lint.yml .'"
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.1"
    hooks:
      - id: editorconfig-checker
        args:
          - "--config"
          - "config/lint/.ecrc"
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args:
          - --config
          - "config/lint/.hadolint.yaml"
          - --verbose
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - id: markdownlint-docker
        args:
          - --config
          - "config/lint/.markdown-lint.yaml"
          - --dot
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.24
    hooks:
      - id: actionlint-docker
  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
        args:
          - "--check"
          - "--diff"
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args:
          - "--check"
          - "--diff"
          - "--settings-file"
          - "config/lint/.isort.cfg"
        pass_filenames: true
  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
        args:
          - "--check"
          - "--diff"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --install-types
          - --non-interactive
          - --verbose
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        args:
          - "--benchmark"
          - "--config=config/lint/.flake8"
          - "--verbose"
          - "--statistics"
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: "35.159.5"
    hooks:
      - id: renovate-config-validator
  # Local hooks
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks (Docker)
        language: docker_image
        pass_filenames: false
        entry: zricethezav/gitleaks:v8.15.2 detect
        args:
          - --config
          - "config/lint/.gitleaks.toml"
          - --no-banner
          - --no-git
          - --redact
          - --verbose
      - id: shfmt
        name: shfmt (Docker)
        language: docker_image
        entry: --net none mvdan/shfmt:v3.6.0
        types: [shell]
        exclude_types: [csh, perl, python, ruby, tcsh, zsh]
        args:
          - "--diff"
  # Meta hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
...
