---
- name: Reboot the host
  ansible.builtin.reboot: null
  when:
    # Skip rebooting the host when running a Molecule test because we can't reboot a container
    - molecule_yml is not defined
...
