---
- name: Reboot the host
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when:
    # Skip rebooting the host when running a Molecule test because we can't reboot a container
    - molecule_yml is not defined
...
