---
- hosts: control-machines:cloud-backup-devices:pxe-servers:torrentboxes
  gather_facts: yes
  tasks:
    - name: Ensure required apt packages are installed
      apt:
        autoremove: yes
        cache_valid_time: 3600
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      become: yes
      with_items:
        - apt-transport-https
        - bzip2
        - ca-certificates
        - curl
        - language-pack-en
  roles:
    - role: stevenharradine.locale
      locale_locales:
        - en_US.UTF-8
