---
apt_cache_valid_time: 3600
default_os_packages:
  - name: cron
  - name: dnsutils
  - name: gnupg
  - name: parted
  - name: python3-venv
  - name: xz-utils
dphys_swapfile_service_name: dphys-swapfile
fail2ban_configuration_directories:
  - path: "{{ fail2ban_configuration_directory }}"
    state: "{{ security_fail2ban_enabled | ternary('directory', 'absent') }}"
fail2ban_packages:
  - name: fail2ban
    state: "{{ security_fail2ban_enabled | ternary('present', 'absent') }}"
fail2ban_service_name: fail2ban
fail2ban_sshd_enable_systemd_backend: true
monitoring_os_packages:
  - name: smartmontools
    state: "{{ configure_monitoring | ternary('present', 'absent') }}"
security_ssh_config_path: /etc/ssh/sshd_config
security_sshd_name: ssh
ssh_os_packages:
  - name: openssh-server
    state: "{{ configure_ssh | ternary('present', 'absent') }}"
sshd_path: /usr/sbin/sshd
tailscale_package_repository_key_file_path: /etc/apt/trusted.gpg.d/tailscale-archive-keyring.gpg
tailscale_package_repository_url: "{{ tailscale_base_package_repository_url }}/debian"
unattended_upgrades_packages:
  - name: unattended-upgrades
    state: "{{ security_unattended_upgrades_enabled | ternary('present', 'absent') }}"
unattended_upgrades_service_name: unattended-upgrades
wifi_os_packages:
  - name: "wpasupplicant"
    state: "{{ configure_wifi | ternary('present', 'absent') }}"
wpa_supplicant_service_name: wpa_supplicant
...
