---
docker_compose_up_items: []
docker_compose_services_to_restart: []
docker_system_prune_service_name: docker-system-prune
docker_system_prune_timer_file_name: "{{ docker_system_prune_service_name }}.timer"
docker_os_services:
  - enabled: true
    service_name: "{{ docker_system_prune_timer_file_name }}"
    service_state: "{{ configure_monitoring | ternary('started', 'stopped') }}"
docker_templates_to_render:
  - src: "docker/system-prune-timer/{{ docker_system_prune_service_name }}.service.jinja"
    dest: "{{ systemd_system_services_configuration_directory }}/{{ docker_system_prune_service_name }}.service"
    state: "{{ configure_docker | ternary('file', 'absent') }}"
    os_services_to_restart:
      - "{{ docker_system_prune_service_name }}"
  - src: "docker/system-prune-timer/{{ docker_system_prune_timer_file_name }}.jinja"
    dest: "{{ systemd_system_services_configuration_directory }}/{{ docker_system_prune_timer_file_name }}"
    state: "{{ configure_docker | ternary('file', 'absent') }}"
    os_services_to_restart:
      - "{{ docker_system_prune_service_name }}"
