---
configure_dphys_swapfile: true
# Got those from v4l2-ctl --list-devices
frigate_gpu_decode_devices:
  - /dev/media0
  - /dev/media1
  - /dev/media2
  - /dev/media3
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/video18
  - /dev/video19
  - /dev/video20
  - /dev/video21
  - /dev/video22
  - /dev/video23
  - /dev/video31
fail2ban_sshd_enable_systemd_backend: false
frigate_ffmpeg_harware_acceleration_arguments: preset-rpi-64-h264
raspberry_pi_config_file_path: "/boot/config.txt"
raspberri_pi_os_os_packages:
  - name: i2c-tools
  - name: python3-rpi.gpio
  - name: python3-smbus
  - name: raspi-gpio
raspberry_pi_sense_hat_config_txt_values:
  # Force enable the sense hat overlay
  dtoverlay: rpi-sense
raspberry_pi_sense_hat_apt_packages:
  - name: sense-hat
    state: "{{ has_sense_hat | ternary('present', 'absent') }}"
tailscale_package_repository_url: "{{ tailscale_base_package_repository_url }}/raspbian"
...
