---
restic_backup_default_backup_job_target_directory: "{{ restic_backup_repositories_default_path }}/{{ restic_backup_workloads_job_name }}"
restic_backup_default_backup_job_docker_compose_profile: restic-backup-job
restic_backup_workloads_job_name: "restic-backup-workloads"
restic_configuration_directories:
  - path: "{{ restic_configuration_directory_path }}"
    state: "{{ configure_backup_restic | ternary('directory', 'absent') }}"
restic_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/restic"
restic_default_backup_jobs:
  - directories_to_backup:
      - source_host_directory: "{{ home_lab_configuration_directory_path }}"
        container_mount_destination_directory: "{{ home_lab_configuration_directory_path }}"
      - source_host_directory: "{{ home_lab_runtime_directory_path }}"
        container_mount_destination_directory: "{{ home_lab_runtime_directory_path }}"
    job_name: "{{ restic_backup_workloads_job_name }}"
    job_schedule: "01:00:00"
    restic_forget_policy: "{{ restic_forget_policies.daily_7_days }}"
    # In seconds
    restic_monitoring_refresh_interval: 43200
    restic_prometheus_exporter_port: 9300
    restic_repository_host_path: "{{ restic_backup_default_backup_job_target_directory }}"
    restic_repository_password: "{{ restic_backup_default_backup_job_repository_password }}"
restic_default_backup_target_directories:
  - path: "{{ restic_backup_default_backup_job_target_directory }}"
    state: "{{ configure_backup_restic | ternary('directory', 'absent') }}"
restic_docker_compose_up_items:
  - compose_file_path: "{{ restic_docker_compose_destination_file_path }}"
    enable_containerized_services: "{{ configure_backup_restic }}"
    pull_container_images: "{{ configure_backup_restic }}"
    # Start restic so we know if backup and monitoring jobs work
    start_containerized_services: "{{ start_restic | default(configure_backup_restic) }}"
restic_configuration_source_directory_path: "config/restic"
restic_docker_compose_destination_file_path: "{{ restic_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
restic_files_to_configure:
  - src: "{{ restic_configuration_source_directory_path }}/{{ default_dockerfile_file_name }}"
    dest: "{{ restic_configuration_directory_path }}/{{ default_dockerfile_file_name }}"
    state: "{{ configure_backup_restic | ternary('file', 'absent') }}"
  - src: "{{ restic_configuration_source_directory_path }}/entrypoint.sh"
    dest: "{{ restic_configuration_directory_path }}/entrypoint.sh"
    state: "{{ configure_backup_restic | ternary('file', 'absent') }}"
restic_repository_container_destination_path: /var/lib/restic/repository
restic_templates_source_directory_path: restic
restic_templates_to_render:
  - src: "{{ restic_templates_source_directory_path }}/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ restic_docker_compose_destination_file_path }}"
    state: "{{ configure_backup_restic | ternary('file', 'absent') }}"
    docker_compose_services_to_restart: "{{ restic_docker_compose_up_items }}"
    # This file may contain secrets, so we want to restrict access to the owner and group only
    # (defaults to root:root)
    mode: "0640"

restic_forget_policies:
  daily_7_days:
    # Keep daily snapshots for the last week
    - --keep-within-daily 7d
  default:
    # Keep daily snapshots for the last week
    - --keep-within-daily 7d
    # Keep weekly snapshots for the last month
    - --keep-within-weekly 1m
    # Keep monthly snapshots for the last year
    - --keep-within-monthly 1y
    # Keep yearly snapshots for the last 10 years
    - --keep-within-yearly 10y
