---
restic_configuration_directories:
  - path: "{{ restic_configuration_directory_path }}"
    state: "{{ configure_backup_restic | ternary('directory', 'absent') }}"
restic_configuration_directory_path: "{{ home_lab_configuration_directory_path }}/restic"
restic_docker_compose_up_items:
  - compose_file_path: "{{ restic_docker_compose_destination_file_path }}"
    enable_containerized_services: "{{ configure_backup_restic }}"
    pull_container_images: "{{ configure_backup_restic }}"
    # Don't start Restic because we manage it using systemd timers
    start_containerized_services: false
    stop_containerized_services: "{{ stop_restic | default(false) }}"
restic_configuration_source_directory_path: "config/restic"
restic_docker_compose_destination_file_path: "{{ restic_configuration_directory_path }}/{{ default_docker_compose_file_name }}"
restic_files_to_configure:
  - src: "{{ restic_configuration_source_directory_path }}/{{ default_dockerfile_file_name }}"
    dest: "{{ restic_configuration_directory_path }}/{{ default_dockerfile_file_name }}"
    state: "{{ configure_backup_restic | ternary('file', 'absent') }}"
  - src: "{{ restic_configuration_source_directory_path }}/entrypoint.sh"
    dest: "{{ restic_configuration_directory_path }}/entrypoint.sh"
    state: "{{ configure_backup_restic | ternary('file', 'absent') }}"
restic_repository_container_destination_path: /var/lib/restic/repository
restic_templates_source_directory_path: restic
restic_templates_to_render:
  - src: "{{ restic_templates_source_directory_path }}/{{ default_docker_compose_file_name }}.jinja"
    dest: "{{ restic_docker_compose_destination_file_path }}"
    state: "{{ configure_backup_restic | ternary('file', 'absent') }}"
    docker_compose_services_to_restart: "{{ restic_docker_compose_up_items }}"
    # This file may contain secrets, so we want to restric access to the owner and group only
    # (defaults to root:root)
    mode: "0640"
...
