---
- name: Reboot host and wait for it to restart
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: Restart docker
  become: true
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: "restarted"

- name: Restart journald
  become: true
  ansible.builtin.service:
    name: "systemd-journald"
    state: "restarted"

- name: Restart ssh
  become: true
  ansible.builtin.service:
    name: "{{ security_sshd_name }}"
    state: "restarted"
...
