---
name: Build Ansible roles

on:
  push:
    paths:
      - "docker/ansible/**"
  pull_request:
    paths:
      - "docker/ansible/**"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Super-Linter
        uses: github/super-linter@v4.9.0
        env:
          DISABLE_ERRORS: false
          ERROR_ON_MISSING_EXEC_BIT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
  test:
    name: Test Ansible roles and playbooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: "Run tests"
        run: |
          set -o errexit
          set -o nounset

          scripts/run-ansible-role-tests.sh "${{ matrix.ansible-artifact-path }}"
...
