---
name: Build firmware images

on:
  push:
    paths:
      - ".github/workflows/build-firmware-images.yaml"
      - "provisioning/esp32/**"
  pull_request:
    paths:
      - ".github/workflows/build-firmware-images.yaml"
      - "provisioning/esp32/**"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Super-Linter
        uses: github/super-linter@v4.8.4
        env:
          DISABLE_ERRORS: false
          ERROR_ON_MISSING_EXEC_BIT: true
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
  build-smart-desk:
    needs:
      - lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: "Build the Smart Desk firmware"
        run: |
          make
        working-directory: provisioning/esp32/smart_desk
...
