---
name: Build OS images

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/build-os-images.yaml"
      - "config/raspberry-pi/**"
      - "config/seed-device/**"
      - "docker/os-image-builder/**"
  pull_request:
    paths:
      - ".github/workflows/build-os-images.yaml"
      - "config/raspberry-pi/**"
      - "config/seed-device/**"
      - "docker/os-image-builder/**"

jobs:
  lint:
    uses: ferrarimarco/home-lab/.github/workflows/lint.yaml@master
  customize-preinstalled-os-images:
    env:
      OS_BUILDER_CONTAINER_IMAGE_ID: "ferrarimarco/os-image-builder:latest"
    needs:
      - lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the OS image builder container image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: docker/os-image-builder
          load: true
          push: false
          tags: "${{ env.OS_BUILDER_CONTAINER_IMAGE_ID }}"
      - name: "Build the image. Config: ${{ matrix.build-configuration-file-path }}"
        run: |
          set -o errexit
          set -o nounset

          TEMP_WORKSPACE_PATH="$(mktemp -d)"
          export TEMP_WORKSPACE_PATH

          RESULTS_FILE_PATH="${TEMP_WORKSPACE_PATH}/results.out"
          export RESULTS_FILE_PATH

          BUILD_CONFIGURATION_FILE_PATH="${{ matrix.build-configuration-file-path }}"
          export BUILD_CONFIGURATION_FILE_PATH

          scripts/build-os-image.sh

          echo "OS image build completed for ${BUILD_CONFIGURATION_FILE_PATH}."
          echo "Appending the build result file (${RESULTS_FILE_PATH}) contents to GITHUB_ENV..."
          cat "${RESULTS_FILE_PATH}" >>"${GITHUB_ENV}"
      - uses: actions/upload-artifact@v2
        name: Upload ${{ env.CUSTOMIZED_COMPRESSED_IMAGE_FILE_NAME }}
        with:
          if-no-files-found: error
          name: ${{ env.CUSTOMIZED_COMPRESSED_IMAGE_FILE_NAME }}
          path: |
            ${{ env.CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH }}
    strategy:
      matrix:
        build-configuration-file-path:
          - "${GITHUB_WORKSPACE}/config/raspberry-pi/raspberry-pi-os-bullseye-arm64.conf"
          - "${GITHUB_WORKSPACE}/config/seed-device/os-images/ubuntu-20.04-cidata-iso-seed-device.conf"
  update-release-draft:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    uses: ferrarimarco/home-lab/.github/workflows/draft-release.yaml@master
  upload-images-to-release:
    needs:
      - customize-preinstalled-os-images
      - update-release-draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts to upload
        uses: actions/download-artifact@v2
      - name: "Upload artifacts to the ${{ needs.update-release-draft.outputs.release-tag-name }} release"
        run: |
          ls ./**/*.${{ matrix.artifact-file-extension }}  >/dev/null && gh release upload "${{ needs.update-release-draft.outputs.release-tag-name }}" ./**/*.${{ matrix.artifact-file-extension }} --clobber
    strategy:
      matrix:
        artifact-file-extension:
          - xz
...
