---
name: Build OS images

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    paths:
      - ".github/workflows/build-os-images.yaml"
      - "provisioning/os-images/**"
  pull_request:
    paths:
      - ".github/workflows/build-os-images.yaml"
      - "provisioning/os-images/**"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Super-Linter
        uses: github/super-linter@v4.8.5
        env:
          DISABLE_ERRORS: false
          ERROR_ON_MISSING_EXEC_BIT: true
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
  customize-preinstalled-os-images:
    env:
      OS_BUILDER_CONTAINER_IMAGE_ID: "ferrarimarco/os-image-builder:latest"
    needs:
      - lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set environment variables
        run: |
          TEMP_WORKSPACE_PATH="$(mktemp -d)"
          {
            echo "TEMP_WORKSPACE_PATH=${TEMP_WORKSPACE_PATH}"
            echo "BUILD_CONFIGURATION_FILE_NAME=$(basename "${{ matrix.build-configuration-file-path }}")"
            echo "BUILD_CONFIGURATION_DIRECTORY_PATH=$(dirname "${{ matrix.build-configuration-file-path }}")"
            echo "RESULTS_FILE_PATH=${TEMP_WORKSPACE_PATH}/results.out"
          } >>"${GITHUB_ENV}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the OS image builder container image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: provisioning/os-images/docker
          load: true
          push: false
          tags: "${{ env.OS_BUILDER_CONTAINER_IMAGE_ID }}"
      - name: "Generate the cloud-init datasource ISO. Config: ${{ matrix.build-configuration-file-path }}"
        run: |
          docker run \
            --privileged \
            --user "$(id -u):$(id -g)" \
            -v /dev:/dev \
            -v "${TEMP_WORKSPACE_PATH}":/tmp/workdir \
            -v "${BUILD_CONFIGURATION_DIRECTORY_PATH}":/tmp/config \
            "${OS_BUILDER_CONTAINER_IMAGE_ID}" \
            --build-config /tmp/config/"${BUILD_CONFIGURATION_FILE_NAME}"

          if ! [ -r "${RESULTS_FILE_PATH}" ]; then
            echo "[ERROR]: The build result metadata file is not available at ${RESULTS_FILE_PATH}. Terminating..."
            exit 2
          fi

          echo "Sourcing ${RESULTS_FILE_PATH} to load the variables defined there..."
          # shellcheck source=/dev/null
          . "${RESULTS_FILE_PATH}"

          CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH="${TEMP_WORKSPACE_PATH}/${CUSTOMIZED_COMPRESSED_IMAGE_FILE_NAME}"
          if ! [ -e "${CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH}" ]; then
            echo "Contents of ${TEMP_WORKSPACE_PATH}:"
            ls -alh "${TEMP_WORKSPACE_PATH}"
            echo "[ERROR]: The customized compressed image file doesn't exist. Terminating..."
            exit 1
          fi

          echo "Adding the path to the customized compressed image (${CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH}) file to GITHUB_ENV"
          {
            echo "CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH=${CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH}"
          } >>"${GITHUB_ENV}"

          echo "Appending the build result metadata file (${RESULTS_FILE_PATH}) contents to GITHUB_ENV..."
          cat "${RESULTS_FILE_PATH}" >>"${GITHUB_ENV}"
      - name: Test the cloud-init datasource
        run: ./scripts/test-cloud-init-datasource.sh --datasource-image-path "${CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH}"
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: ${{ env.CUSTOMIZED_COMPRESSED_IMAGE_FILE_NAME }}
          path: |
            ${{ env.CUSTOMIZED_COMPRESSED_IMAGE_FILE_PATH }}
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: cloud-init-logs
          path: |
            cloud-init.tar.gz
    strategy:
      matrix:
        build-configuration-file-path:
          - "${GITHUB_WORKSPACE}/provisioning/os-images/config/builds/seed-device/ubuntu-20.04-cidata-iso-seed-device.conf"
  update-release-draft:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    outputs:
      release-tag-name: ${{ steps.draft-release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - id: draft-release
        name: Update release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
  upload-images-to-release:
    needs:
      - customize-preinstalled-os-images
      - update-release-draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Download artifacts to upload
        uses: actions/download-artifact@v2
      - name: "Upload artifacts to the ${{ needs.update-release-draft.outputs.release-tag-name }} release"
        run: |
          ls ./**/*.${{ matrix.artifact-file-extension }}  >/dev/null && gh release upload "${{ needs.update-release-draft.outputs.release-tag-name }}" ./**/*.${{ matrix.artifact-file-extension }} --clobber
    strategy:
      matrix:
        artifact-file-extension:
          - xz
...
