---
name: Build and publish MkDocs website

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      site-destination-path:
        required: true
        type: string
      site-name:
        required: true
        type: string
      site-repository:
        required: true
        type: string
      site-repository-branch:
        required: true
        type: string
      site-source-path:
        default: src
        required: false
        type: string
    secrets:
      repository-github-token:
        required: true

permissions:
  contents: write

jobs:
  build-push-mkdocs-site:
    concurrency:
      # Ref: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      # github.head_ref: head_ref or source branch of the pull request
      # github.ref: ref of the branch that triggered the workflow
      group: ${{ github.workflow }}-build-push-${{ inputs.site-name }}-site-${{ inputs.site-repository-branch }}-${{ github.event_name }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      # Safely map the inputs to environment variables
      SITE_NAME: ${{ inputs.site-name }}
      SITE_SOURCE_PATH: ${{ inputs.site-source-path }}
      SITE_DESTINATION_PATH: ${{ inputs.site-destination-path }}
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Checkout the site repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          path: "$SITE_NAME"
          repository: "${{ inputs.site-repository }}"
          token: "${{ secrets.repository-github-token }}"
      - name: Build the $SITE_NAME site
        run: |
          scripts/run-mkdocs.sh "build" "$SITE_NAME" "./$SITE_SOURCE_PATH" "./$SITE_DESTINATION_PATH"
      - name: Commit and push updates to the $SITE_NAME site
        if: >
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          branch: ${{ inputs.site-repository-branch }}
          commit_message: "chore: update $SITE_NAME site"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          repository: "$SITE_NAME"
