---
name: Build firmware images

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/build-firmware-images.yaml"
      - "config/smart-desk/**"
  pull_request:
    paths:
      - ".github/workflows/build-firmware-images.yaml"
      - "config/smart-desk/**"

jobs:
  build-smart-desk:
    defaults:
      run:
        working-directory: config/smart-desk/esphome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Build the Smart Desk firmware image"
        run: |
          scripts/build.sh
...
