---
name: Build Arduino projects

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/build-arduino-projects.yaml"
      - "config/arduino/**"
      - "scripts/build-arduino-project.sh"
  pull_request:
    paths:
      - ".github/workflows/build-arduino-projects.yaml"
      - "config/arduino/**"
      - "scripts/build-arduino-project.sh"

jobs:
  build-arduino-projects:
    concurrency:
      # Ref: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      # github.head_ref: head_ref or source branch of the pull request
      # github.ref: ref of the branch that triggered the workflow
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ github.event_name }}-${{ matrix.arduino-board.fqbn }}-${{ matrix.arduino-project.project-context-path }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "Build the ${{ matrix.arduino-project.project-id }} Arduino project"
        run: |
          scripts/build-arduino-project.sh \
            "${{ matrix.arduino-project.project-context-path }}" \
            "${{ matrix.arduino-board.fqbn }}"
    strategy:
      matrix:
        arduino-board:
          - board-name: "Arduino 33 BLE Sense"
            core-id: "arduino:mbed_nano"
            fqbn: "arduino:mbed_nano:nano33ble"
        arduino-project:
          - project-id: arduino-33-ble-sense
            project-context-path: config/arduino/arduino-33-ble-sense
