---
name: Build OS images

on:
  push:
    paths:
      - "provisioning/os-images/**"
  pull_request:
    paths:
      - "provisioning/os-images/**"

jobs:
  build-os-images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: "Build OS image: ${{ matrix.build-configuration-file-path }}"
        run: |
          sudo ./provisioning/os-images/scripts/build-os-image.sh \
          --build-config "${{ matrix.build-configuration-file-path }}"
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: os-image
          path: "**/*.xz"
    strategy:
      matrix:
        build-configuration-file-path:
          - provisioning/os-images/config/builds/ubuntu-20.04.2-arm64-raspberry-pi-4-seed-device.conf
...
