---
name: Build firmware images

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    paths:
      - ".github/workflows/build-firmware-images.yaml"
      - "config/smart-desk/**"
  pull_request:
    paths:
      - ".github/workflows/build-firmware-images.yaml"
      - "config/smart-desk/**"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Super-Linter
        uses: github/super-linter@v4.9.0
        env:
          DISABLE_ERRORS: false
          ERROR_ON_MISSING_EXEC_BIT: true
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
  build-smart-desk:
    defaults:
      run:
        working-directory: config/smart-desk/esphome
    needs:
      - lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "Build the Smart Desk firmware image"
        run: |
          scripts/build.sh
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: smart-desk.bin.xz
          # working-directory has no effect on this action, so we need to set the full path anyway.
          # See https://github.com/actions/upload-artifact/issues/246
          path: |
            config/smart-desk/esphome/.esphome/build/smart-desk/.pioenvs/smart-desk/firmware-factory.bin.xz
  update-release-draft:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    outputs:
      release-tag-name: ${{ steps.draft-release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - id: draft-release
        name: Update release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
  upload-images-to-release:
    needs:
      - build-smart-desk
      - update-release-draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts to upload
        uses: actions/download-artifact@v2
      - name: "Upload artifacts to the ${{ needs.update-release-draft.outputs.release-tag-name }} release"
        run: |
          ls ./**/*.${{ matrix.artifact-file-extension }}  >/dev/null && gh release upload "${{ needs.update-release-draft.outputs.release-tag-name }}" ./**/*.${{ matrix.artifact-file-extension }} --clobber
    strategy:
      matrix:
        artifact-file-extension:
          - xz
...
