---
name: Dependency Review
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Review dependencies
        uses: actions/dependency-review-action@v3
...
