---
name: Run Ansible against home lab hosts

permissions:
  contents: read

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null
  workflow_dispatch: null

concurrency:
  group: Home lab
  cancel-in-progress: true

jobs:
  test-ansible:
    uses: ./.github/workflows/test-ansible.yaml
  run-ansible:
    environment: Home lab
    if: github.repository == 'ferrarimarco/home-lab'
    needs:
      - test-ansible
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - uses: actions/checkout@v3
      - name: Run Ansible
        env:
          ADDITIONAL_ANSIBLE_FLAGS: "-CD"
          ANSIBLE_VAULT_PASSWORD: "${{ secrets.ANSIBLE_VAULT_PASSWORD }}"
        run: |
          scripts/run-ansible.sh
...
