---
name: Run Ansible against home lab hosts

permissions:
  contents: read

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null
  workflow_dispatch: null

jobs:
  run-ansible:
    environment: Home lab
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - run: |
          ADDITIONAL_ANSIBLE_FLAGS="-CD" scripts/run-ansible.sh
...
