---
name: Draft release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
  workflow_call:
    outputs:
      release-tag-name:
        description: Release tag name
        value: ${{ jobs.update-release-draft.outputs.release-tag-name }}

jobs:
  update-release-draft:
    outputs:
      release-tag-name: ${{ steps.draft-release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - id: draft-release
        name: Update release draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yaml
...
