---
name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Super-Linter
        uses: github/super-linter@v4.5.1
        env:
          DISABLE_ERRORS: false
          ERROR_ON_MISSING_EXEC_BIT: true
          LINTER_RULES_PATH: .linters
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
