---
name: Lint

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null
  workflow_call: null

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run pre-commit"
        run: |
          set -o errexit
          set -o nounset

          scripts/run-pre-commit.sh
...
