---
name: Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master

# Don't grant any access by default
permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-main-release
      cancel-in-progress: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4.1.4
        id: release
        with:
          config-file: .github/release-please/release-please-config.json
          manifest-file: .github/release-please/.release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
