---
on:
  release:
    types: ['published']

jobs:
  build-upload-os-images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: "Build OS image: ${{ matrix.build-configuration-file-path }}"
        run: |
          sudo ./provisioning/os-images/scripts/build-os-image.sh \
          --build-config "${{ matrix.build-configuration-file-path }}"
      - name: "Upload the OS image: ${{ matrix.build-configuration-file-path }}"
        run: |
          gh release upload "${GITHUB_REF}" "**/*.xz" --clobber
    strategy:
      matrix:
        build-configuration-file-path:
          - provisioning/os-images/config/builds/ubuntu-20.04.2-arm64-raspberry-pi-4-seed-device.conf
...
