---
name: Renovate

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/renovate.yaml"
      - ".github/renovate.json"
  pull_request:
    paths:
      - ".github/workflows/renovate.yaml"
      - ".github/renovate.json"
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: null

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Enable dry run if required
        if: ${{ github.ref_name != github.event.repository.default_branch }}
        run: |
          set -o errexit
          set -o nounset

          echo "Enable Dependabot dry run"
          echo "RENOVATE_DRY_RUN=full" >>"${GITHUB_ENV}"
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        env:
          LOG_LEVEL: 'debug'
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
...
