---
name: Renovate

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: null

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Enable Renovatebot debug logging if necessary
        run: |
          set -o errexit
          set -o nounset

          if [ "${ACTIONS_RUNNER_DEBUG:-}" = "true" ]; then
            echo "Enabling Renovatebot debug output..."
            echo "LOG_LEVEL=debug" >> "${GITHUB_ENV}"
          fi
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.229.0
        env:
          LOG_LEVEL: 'debug'
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
...
