---
name: Test shell scripts

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions:
  contents: read

jobs:
  test-ansible:
    concurrency:
      # Ref: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      # github.head_ref: head_ref or source branch of the pull request
      # github.ref: ref of the branch that triggered the workflow
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ github.event_name }}-${{ matrix.test_script_path }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.test_script_path }}
        run: |
          set -o errexit
          set -o nounset
          "${{ matrix.test_script_path }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_script_path:
          - test/scripts/build-python-venv-test.sh
