---
name: Test Ansible collections, roles, playbooks

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/test-ansible.yaml"
      - "config/ansible/**"
      - "docker/ansible/**"
      - "scripts/common.sh"
      - "scripts/run-ansible.sh"
  pull_request:
    paths:
      - ".github/workflows/test-ansible.yaml"
      - "config/ansible/**"
      - "docker/ansible/**"
      - "scripts/common.sh"
      - "scripts/run-ansible.sh"

jobs:
  test-ansible:
    env:
      ANSIBLE_TEST_CONTAINER_IMAGE_ID: "${{ github.repository }}-ansible"
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # This might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run molecule
        run: |
          set -o errexit
          set -o nounset

          ANSIBLE_TEST_DISTRO=${{ matrix.test_container_image_id }}
          export ANSIBLE_TEST_DISTRO

          ANSIBLE_TEST_PLAYBOOK_NAME=${{ matrix.test_playbook_name }}
          export ANSIBLE_TEST_PLAYBOOK_NAME

          scripts/run-ansible.sh "molecule test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_container_image_id:
          - "geerlingguy/docker-debian11-ansible:latest"
          - "geerlingguy/docker-debian12-ansible:latest"
        test_playbook_name:
          - bootstrap
          - container-engine
          - main
...
