---
name: Test Ansible collections, roles, playbooks

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/test-ansible.yaml"
      - "docker/ansible/**"
  pull_request:
    paths:
      - ".github/workflows/test-ansible.yaml"
      - "docker/ansible/**"

jobs:
  test-ansible:
    env:
      ANSIBLE_TEST_CONTAINER_IMAGE_ID: "${{ github.repository }}-ansible"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run molecule
        run: |
          set -o errexit
          set -o nounset

          MOLECULE_DISTRO=${{ matrix.test_container_image_id }}
          export MOLECULE_DISTRO

          scripts/run-ansible.sh "molecule test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_container_image_id:
          - "geerlingguy/docker-debian11-ansible:latest"
...
