---
name: Test Ansible collections, roles, playbooks

on: # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/test-ansible.yaml"
      - "config/ansible/**"
      - "docker/ansible/**"
      - "scripts/common.sh"
      - "scripts/run-ansible.sh"
      # Don't test playbooks when editing these files because we have dedicated
      # tests (build-container-images.yaml for the Dockerfiles,
      # test-python-requirements.yaml for the requirements files)
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/dependency-updates-helper/Dockerfile"
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/monitoring-apt/requirements.txt"
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/monitoring-ont/requirements.txt"
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/restic/Dockerfile"
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/sense-hat-exporter/requirements.txt"
  pull_request:
    paths:
      - ".github/workflows/test-ansible.yaml"
      - "config/ansible/**"
      - "docker/ansible/**"
      - "scripts/common.sh"
      - "scripts/run-ansible.sh"
      # Don't test playbooks when editing these files because we have dedicated
      # tests (build-container-images.yaml for the Dockerfiles,
      # test-python-requirements.yaml for the requirements files)
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/dependency-updates-helper/Dockerfile"
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/monitoring-apt/requirements.txt"
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/monitoring-ont/requirements.txt"
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/restic/Dockerfile"
      - "!config/ansible/roles/ferrarimarco_home_lab_node/files/config/sense-hat-exporter/requirements.txt"

permissions:
  contents: read

jobs:
  test-ansible:
    concurrency:
      # Ref: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      # github.head_ref: head_ref or source branch of the pull request
      # github.ref: ref of the branch that triggered the workflow
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ github.event_name }}-${{ matrix.test_container_image_id }}-${{ matrix.test_playbook_name }}
      cancel-in-progress: true
    env:
      ANSIBLE_TEST_CONTAINER_IMAGE_ID: "${{ github.repository }}-ansible:test"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      # Build the container image here instead of letting the script build it
      # so that all the test jobs share the container image layers using the
      # build cache.
      - name: Build the Ansible container image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          build-contexts: |
            ansible-configuration=config/ansible
          cache-from: type=gha,scope=ansible-molecule
          cache-to: type=gha,mode=max,scope=ansible-molecule
          context: docker/ansible
          load: true
          tags: ${{ env.ANSIBLE_TEST_CONTAINER_IMAGE_ID }}
          target: molecule
      - name: Run molecule
        env:
          ANSIBLE_CONTAINER_IMAGE_ID: ${{ env.ANSIBLE_TEST_CONTAINER_IMAGE_ID }}
          ANSIBLE_CONTAINER_IMAGE_SKIP_BUILD: "true"
        run: |
          set -o errexit
          set -o nounset

          ANSIBLE_TEST_DISTRO=${{ matrix.test_container_image_id }}
          export ANSIBLE_TEST_DISTRO

          ANSIBLE_TEST_PLAYBOOK_NAME=${{ matrix.test_playbook_name }}
          export ANSIBLE_TEST_PLAYBOOK_NAME

          scripts/run-ansible.sh "molecule test"
    runs-on: ubuntu-latest
    strategy:
      # Run all the tests to completion to report the result of each playbook
      fail-fast: false
      matrix:
        test_container_image_id:
          - "geerlingguy/docker-debian12-ansible:latest"
        test_playbook_name:
          - boot-bare-metal
          - bootstrap
          - container-engine
          - coral
          - update-os-packages
          - proxmox-node
          - setup-disks
          - main
